Repository Skyscanner/backpack, pull requests merged in 2023-12, with the labels that each got.

#3109 [NO JIRA] Add babel-plugin-react-docgen as a dependency
  package-lock.json
  package.json
Labels: dependencies, skip-changelog

#3108 [THES-87] [BpkBottomSheet] implementing component
  README.md
  examples/bpk-component-bottom-sheet/examples.module.css
  examples/bpk-component-bottom-sheet/examples.module.scss
  examples/bpk-component-bottom-sheet/examples.tsx
  examples/bpk-component-bottom-sheet/stories.js
  packages/README.md
  packages/bpk-component-bottom-sheet/README.md
  packages/bpk-component-bottom-sheet/index.d.ts
  packages/bpk-component-bottom-sheet/index.ts
  packages/bpk-component-bottom-sheet/src/BpkBottomSheet-test.tsx
  packages/bpk-component-bottom-sheet/src/BpkBottomSheet.d.ts
  packages/bpk-component-bottom-sheet/src/BpkBottomSheet.module.css
  packages/bpk-component-bottom-sheet/src/BpkBottomSheet.module.scss
  packages/bpk-component-bottom-sheet/src/BpkBottomSheet.tsx
  packages/bpk-component-bottom-sheet/src/BpkBottomSheetInner-test.tsx
  packages/bpk-component-bottom-sheet/src/BpkBottomSheetInner.d.ts
  packages/bpk-component-bottom-sheet/src/BpkBottomSheetInner.module.css
  packages/bpk-component-bottom-sheet/src/BpkBottomSheetInner.module.scss
  packages/bpk-component-bottom-sheet/src/BpkBottomSheetInner.tsx
  packages/bpk-component-bottom-sheet/src/__snapshots__/BpkBottomSheet-test.tsx.snap
  packages/bpk-component-bottom-sheet/src/__snapshots__/BpkBottomSheetInner-test.tsx.snap
  packages/bpk-component-bottom-sheet/src/accessibility-test.tsx
Labels: minor

#3120 [BpkAutosuggest]: Fixing autosuggest component
  packages/bpk-component-autosuggest/src/BpkAutosuggestSuggestion.js
Labels: patch

#3121 NOJIRA - BpkBottomSheet "out" console error fix
  packages/bpk-component-bottom-sheet/src/BpkBottomSheetInner.tsx
Labels: patch

#3122 [DTO-4949][BpkNavigationBar] Remove prop-types from navbar
  packages/bpk-component-navigation-bar/src/BpkNavigationBar.tsx
  packages/bpk-component-navigation-bar/src/BpkNavigationBarButtonLink.tsx
  packages/bpk-component-navigation-bar/src/BpkNavigationBarIconButton.tsx
Labels: minor

#3131 LOOM-1122 Backpack Nudger RTL Bug + -
  packages/bpk-component-nudger/src/BpkNudger.module.css
  packages/bpk-component-nudger/src/BpkNudger.module.scss
Labels: patch

#3132 [BpkBottomSheet] add event tracking option to close
  packages/bpk-component-bottom-sheet/src/BpkBottomSheet.d.ts
  packages/bpk-component-bottom-sheet/src/BpkBottomSheet.tsx
Labels: patch
