Repository Skyscanner/backpack, pull requests merged in 2023-05, with the labels that each got.

#2829 [KOA-5200]: Icon component to TS
  packages/bpk-component-icon/all.tsx
  packages/bpk-component-icon/index.d.ts
  packages/bpk-component-icon/index.tsx
  packages/bpk-component-icon/src/__snapshots__/classNameModifierHOCFactory-test.tsx.snap
  packages/bpk-component-icon/src/__snapshots__/withAlignment-test.tsx.snap
  packages/bpk-component-icon/src/__snapshots__/withDescription-test.tsx.snap
  packages/bpk-component-icon/src/classNameModifierHOCFactory-test.tsx
  packages/bpk-component-icon/src/classNameModifierHOCFactory.d.ts
  packages/bpk-component-icon/src/classNameModifierHOCFactory.tsx
  packages/bpk-component-icon/src/withAlignment-test.tsx
  packages/bpk-component-icon/src/withAlignment.d.ts
  packages/bpk-component-icon/src/withAlignment.tsx
  packages/bpk-component-icon/src/withDescription-test.tsx
  packages/bpk-component-icon/src/withDescription.d.ts
  packages/bpk-component-icon/src/withDescription.tsx
  packages/bpk-component-icon/src/withRtlSupport.d.ts
  packages/bpk-component-icon/src/withRtlSupport.tsx
Labels: minor

#2838 Fix BpkDialog type
  packages/bpk-component-dialog/src/common-types.ts
Labels: patch

#2840 Fix BpkPrice className warning
  packages/bpk-component-price/src/BpkPrice.js
  packages/bpk-component-price/src/__snapshots__/BpkPrice-test.js.snap
Labels: patch

#2841 [NO JIRA]: Add missing build cache creation for releases
  .github/workflows/release.yml
Labels: skip-changelog

#2837 [KOA-5945]: Button v2 rewrite
  .storybook/__image_snapshots__/storyshots-test-js-visual-tests-bpk-component-button-visual-test-1-snap.png
  examples/bpk-component-button/examples.js
  examples/bpk-component-button/stories.js
  packages/bpk-component-button/README.md
  packages/bpk-component-button/docs/button-v1-readme.md
  packages/bpk-component-button/docs/migrating-from-v1-to-v2.md
  packages/bpk-component-button/index.js
  packages/bpk-component-button/src/BpkButtonV2/BpkButton-test.tsx
  packages/bpk-component-button/src/BpkButtonV2/BpkButton.d.ts
  packages/bpk-component-button/src/BpkButtonV2/BpkButton.module.css
  packages/bpk-component-button/src/BpkButtonV2/BpkButton.module.scss
  packages/bpk-component-button/src/BpkButtonV2/BpkButton.tsx
  packages/bpk-component-button/src/BpkButtonV2/__snapshots__/BpkButton-test.tsx.snap
  packages/bpk-component-button/src/BpkButtonV2/accessibility-test.tsx
  packages/bpk-component-button/src/BpkButtonV2/common-types.d.ts
  packages/bpk-component-button/src/BpkButtonV2/common-types.tsx
Labels: minor

#2839 [BD-6906] Support mapId
  packages/bpk-component-map/README.md
  packages/bpk-component-map/src/BpkMap.js
Labels: minor

#2847 [NO JIRA] Update contribution guide to make TS the default
  CONTRIBUTING.md
Labels: skip-changelog

#2846 [NO JIRA] Fix transpilation scripts to move css and types files
  CONTRIBUTING.md
  packages/bpk-component-button/src/BpkButtonV2/BpkButton.module.css
  packages/bpk-component-floating-notification/src/BpkFloatingNotification.module.css
  scripts/transpilation/copy-css.js
  scripts/transpilation/copy-types.js
Labels: patch

#2852 [NO JIRA] Update import path BpkButtonV2 in migrating docs
  packages/bpk-component-button/docs/migrating-from-v1-to-v2.md
  packages/bpk-component-button/index.js
Labels: patch

#2855 [NO JIRA] Update experimentation guidelines
  CONTRIBUTING.md
Labels: skip-changelog

#2856 [KOA-6123] Migrate card component to TS
  packages/bpk-component-card/README.md
  packages/bpk-component-card/index.d.ts
  packages/bpk-component-card/index.ts
  packages/bpk-component-card/src/BpkCard-test.tsx
  packages/bpk-component-card/src/BpkCard.d.ts
  packages/bpk-component-card/src/BpkCard.tsx
  packages/bpk-component-card/src/BpkCardWrapper-test.tsx
  packages/bpk-component-card/src/BpkCardWrapper.d.ts
  packages/bpk-component-card/src/BpkCardWrapper.tsx
  packages/bpk-component-card/src/BpkDividedCard-test.tsx
  packages/bpk-component-card/src/BpkDividedCard.d.ts
  packages/bpk-component-card/src/BpkDividedCard.tsx
  packages/bpk-component-card/src/__snapshots__/BpkCard-test.tsx.snap
  packages/bpk-component-card/src/__snapshots__/BpkCardWrapper-test.tsx.snap
  packages/bpk-component-card/src/__snapshots__/BpkDividedCard-test.tsx.snap
Labels: minor

#2857 [KOA-6122] Migrate RTL toggle to TS
  .eslintignore
  packages/bpk-component-rtl-toggle/index.d.ts
  packages/bpk-component-rtl-toggle/index.ts
  packages/bpk-component-rtl-toggle/src/BpkRtlToggle-test.tsx
  packages/bpk-component-rtl-toggle/src/BpkRtlToggle.d.ts
  packages/bpk-component-rtl-toggle/src/BpkRtlToggle.tsx
  packages/bpk-component-rtl-toggle/src/__snapshots__/BpkRtlToggle-test.tsx.snap
  packages/bpk-component-rtl-toggle/src/__snapshots__/updateOnDirectionChange-test.tsx.snap
  packages/bpk-component-rtl-toggle/src/accessibility-test.tsx
  packages/bpk-component-rtl-toggle/src/updateOnDirectionChange-test.tsx
  packages/bpk-component-rtl-toggle/src/updateOnDirectionChange.d.ts
  packages/bpk-component-rtl-toggle/src/updateOnDirectionChange.tsx
  packages/bpk-component-rtl-toggle/src/utils.d.ts
  packages/bpk-component-rtl-toggle/src/utils.ts
Labels: minor

#2848 [KOA-5186] Migrate chip component to TS
  packages/bpk-component-chip/README.md
  packages/bpk-component-chip/index.d.ts
  packages/bpk-component-chip/index.ts
  packages/bpk-component-chip/src/BpkDismissibleChip-test.tsx
  packages/bpk-component-chip/src/BpkDismissibleChip.d.ts
  packages/bpk-component-chip/src/BpkDismissibleChip.tsx
  packages/bpk-component-chip/src/BpkDropdownChip-test.tsx
  packages/bpk-component-chip/src/BpkDropdownChip.d.ts
  packages/bpk-component-chip/src/BpkDropdownChip.tsx
  packages/bpk-component-chip/src/BpkSelectableChip-test.tsx
  packages/bpk-component-chip/src/BpkSelectableChip.d.ts
  packages/bpk-component-chip/src/BpkSelectableChip.tsx
  packages/bpk-component-chip/src/__snapshots__/BpkDismissibleChip-test.tsx.snap
  packages/bpk-component-chip/src/__snapshots__/BpkDropdownChip-test.tsx.snap
  packages/bpk-component-chip/src/__snapshots__/BpkSelectableChip-test.tsx.snap
  packages/bpk-component-chip/src/accessibility-test.tsx
  packages/bpk-component-chip/src/commonTypes.d.ts
  packages/bpk-component-chip/src/commonTypes.ts
  packages/bpk-component-chip/src/themeAttributes-test.ts
  packages/bpk-component-chip/src/themeAttributes.ts
Labels: minor

#2830 [KOA-5539] Migrate input component to TS
  examples/bpk-component-input/examples.js
  packages/bpk-component-input/index.d.ts
  packages/bpk-component-input/index.ts
  packages/bpk-component-input/src/BpkClearButton-test.tsx
  packages/bpk-component-input/src/BpkClearButton.d.ts
  packages/bpk-component-input/src/BpkClearButton.tsx
  packages/bpk-component-input/src/BpkInput-test.tsx
  packages/bpk-component-input/src/BpkInput.d.ts
  packages/bpk-component-input/src/BpkInput.tsx
  packages/bpk-component-input/src/__snapshots__/BpkClearButton-test.tsx.snap
  packages/bpk-component-input/src/__snapshots__/BpkInput-test.tsx.snap
  packages/bpk-component-input/src/__snapshots__/withOpenEvents-test.tsx.snap
  packages/bpk-component-input/src/accessibility-test.tsx
  packages/bpk-component-input/src/common-types-test.ts
  packages/bpk-component-input/src/common-types.d.ts
  packages/bpk-component-input/src/common-types.ts
  packages/bpk-component-input/src/themeAttributes-test.ts
  packages/bpk-component-input/src/themeAttributes.ts
  packages/bpk-component-input/src/withOpenEvents-test.tsx
  packages/bpk-component-input/src/withOpenEvents.d.ts
  packages/bpk-component-input/src/withOpenEvents.tsx
Labels: minor

#2843 [KOA-5183] Migrate calendar to TS
  packages/bpk-component-calendar/index.d.ts
  packages/bpk-component-calendar/index.ts
  packages/bpk-component-calendar/src/BpkCalendarContainer-test.tsx
  packages/bpk-component-calendar/src/BpkCalendarContainer.d.ts
  packages/bpk-component-calendar/src/BpkCalendarContainer.tsx
  packages/bpk-component-calendar/src/BpkCalendarDate-test.tsx
  packages/bpk-component-calendar/src/BpkCalendarDate.d.ts
  packages/bpk-component-calendar/src/BpkCalendarDate.tsx
  packages/bpk-component-calendar/src/BpkCalendarGrid-test.tsx
  packages/bpk-component-calendar/src/BpkCalendarGrid.d.ts
  packages/bpk-component-calendar/src/BpkCalendarGrid.tsx
  packages/bpk-component-calendar/src/BpkCalendarGridHeader.d.ts
  packages/bpk-component-calendar/src/BpkCalendarGridHeader.tsx
  packages/bpk-component-calendar/src/BpkCalendarGridTransition-test.tsx
  packages/bpk-component-calendar/src/BpkCalendarGridTransition.d.ts
  packages/bpk-component-calendar/src/BpkCalendarGridTransition.tsx
  packages/bpk-component-calendar/src/BpkCalendarNav-test.tsx
  packages/bpk-component-calendar/src/BpkCalendarNav.d.ts
  packages/bpk-component-calendar/src/BpkCalendarNav.tsx
  packages/bpk-component-calendar/src/Week-test.tsx
  packages/bpk-component-calendar/src/Week.d.ts
  packages/bpk-component-calendar/src/Week.tsx
  packages/bpk-component-calendar/src/__snapshots__/BpkCalendarContainer-test.tsx.snap
  packages/bpk-component-calendar/src/__snapshots__/BpkCalendarDate-test.tsx.snap
  packages/bpk-component-calendar/src/__snapshots__/BpkCalendarGrid-test.tsx.snap
  packages/bpk-component-calendar/src/__snapshots__/BpkCalendarGridTransition-test.tsx.snap
  packages/bpk-component-calendar/src/__snapshots__/BpkCalendarNav-test.tsx.snap
  packages/bpk-component-calendar/src/__snapshots__/Week-test.tsx.snap
  packages/bpk-component-calendar/src/__snapshots__/composeCalendar-test.tsx.snap
  packages/bpk-component-calendar/src/accessibility-test.tsx
  packages/bpk-component-calendar/src/composeCalendar-test.tsx
  packages/bpk-component-calendar/src/composeCalendar.d.ts
  packages/bpk-component-calendar/src/composeCalendar.tsx
  packages/bpk-component-calendar/src/custom-proptypes-legacy.js
  packages/bpk-component-calendar/src/custom-proptypes.d.ts
  packages/bpk-component-calendar/src/custom-proptypes.ts
  packages/bpk-component-calendar/src/date-utils.d.ts
  packages/bpk-component-calendar/src/date-utils.ts
  packages/bpk-component-calendar/src/themeAttributes-test.ts
  packages/bpk-component-calendar/src/themeAttributes.ts
  packages/bpk-component-calendar/src/utils.d.ts
  packages/bpk-component-calendar/src/utils.ts
  packages/bpk-component-calendar/test-utils.d.ts
  packages/bpk-component-calendar/test-utils.ts
Labels: minor

#2860 [NO JIRA] Add danger step for type files
  dangerfile.js
Labels: skip-changelog
