Repository Skyscanner/backpack, pull requests merged in 2023-08, with the labels that each got.

#2943 BpkButton: Improve onClick type to Mouse Event
  packages/bpk-component-button/src/BpkButtonV2/common-types.d.ts
  packages/bpk-component-button/src/BpkButtonV2/common-types.tsx
Labels: patch

#2938 [KOA-6044] Bump storybook to v7
  .eslintrc
  .storybook/main.ts
  .storybook/preview.tsx
  .storybook/webpack.config.js
  .stylelintrc.json
  examples/bpk-component-calendar/examples-components.js
  examples/bpk-component-calendar/examples.js
  examples/bpk-component-datatable/examples.js
  examples/bpk-component-flare/examples.js
  package-lock.json
  package.json
  packages/bpk-component-banner-alert/src/AnimateAndFade.tsx
  packages/bpk-component-barchart/src/BpkBarchart.js
  packages/bpk-component-calendar/src/BpkCalendarGridTransition.tsx
  packages/bpk-component-calendar/src/utils.ts
  packages/bpk-component-content-cards/src/BpkContentCard.module.scss
  packages/bpk-component-datepicker/src/BpkDatepicker.tsx
  packages/bpk-component-dialog/src/BpkDialogInner.module.scss
  packages/bpk-component-floating-notification/src/BpkFloatingNotification.module.scss
  packages/bpk-component-horizontal-nav/src/BpkHorizontalNav.js
  packages/bpk-component-infinite-scroll/src/DataSource.js
  packages/bpk-component-infinite-scroll/src/withInfiniteScroll.js
  packages/bpk-component-modal/src/BpkModalInner.module.scss
  packages/bpk-component-modal/src/BpkModalV2/BpKModal.module.scss
  packages/bpk-component-nudger/src/BpkConfigurableNudger.tsx
  packages/bpk-component-scrollable-calendar/src/BpkScrollableCalendarGridList.tsx
  packages/bpk-component-select/src/BpkSelect.js
  packages/bpk-component-skip-link/src/BpkSkipLink.module.scss
  packages/bpk-component-switch/src/BpkSwitch.module.scss
  packages/bpk-component-tooltip/src/BpkTooltip.module.scss
  packages/bpk-theming/src/BpkThemeProvider.js
  packages/package-lock.json
  scripts/transpilation/copy-css.js
  scripts/transpilation/copy-types.js
Labels: skip-changelog

#2949 Fix bpkButton ts imports
  packages/bpk-component-button/src/BpkButtonBase.js
  packages/bpk-component-button/src/BpkButtonDestructive.js
  packages/bpk-component-button/src/BpkButtonFeatured.js
  packages/bpk-component-button/src/BpkButtonLink.js
  packages/bpk-component-button/src/BpkButtonLinkOnDark.js
  packages/bpk-component-button/src/BpkButtonPrimary.js
  packages/bpk-component-button/src/BpkButtonPrimaryOnDark.js
  packages/bpk-component-button/src/BpkButtonPrimaryOnLight.js
  packages/bpk-component-button/src/BpkButtonSecondary.js
  packages/bpk-component-button/src/BpkButtonSecondaryOnDark.js
Labels: patch

#2953 [KOA-6234] Add aria-hidden property to all icons
  package-lock.json
  package.json
  packages/bpk-component-accordion/src/__snapshots__/BpkAccordionItem-test.js.snap
  packages/bpk-component-accordion/src/__snapshots__/withAccordionItemState-test.js.snap
  packages/bpk-component-autosuggest/src/__snapshots__/BpkAutosuggestSuggestion-test.js.snap
  packages/bpk-component-badge/src/__snapshots__/BpkBadge-test.tsx.snap
  packages/bpk-component-banner-alert/src/__snapshots__/BpkBannerAlert-test.tsx.snap
  packages/bpk-component-banner-alert/src/__snapshots__/BpkBannerAlertDismissable-test.tsx.snap
  packages/bpk-component-banner-alert/src/__snapshots__/BpkBannerAlertInner-test.tsx.snap
  packages/bpk-component-banner-alert/src/__snapshots__/withBannerAlertState-test.tsx.snap
  packages/bpk-component-breadcrumb/src/__snapshots__/BpkBreadcrumbItem-test.js.snap
  packages/bpk-component-calendar/src/__snapshots__/BpkCalendarContainer-test.tsx.snap
  packages/bpk-component-calendar/src/__snapshots__/BpkCalendarNav-test.tsx.snap
  packages/bpk-component-chip/src/__snapshots__/BpkDismissibleChip-test.tsx.snap
  packages/bpk-component-chip/src/__snapshots__/BpkDropdownChip-test.tsx.snap
  packages/bpk-component-close-button/src/__snapshots__/BpkCloseButton-test.js.snap
  packages/bpk-component-datatable/src/__snapshots__/BpkDataTable-test.js.snap
  packages/bpk-component-datatable/src/__snapshots__/BpkDataTableHeader-test.js.snap
  packages/bpk-component-dialog/src/__snapshots__/BpkDialog-test.tsx.snap
  packages/bpk-component-drawer/src/__snapshots__/BpkDrawer-test.js.snap
  packages/bpk-component-drawer/src/__snapshots__/BpkDrawerContent-test.js.snap
  packages/bpk-component-fieldset/src/__snapshots__/BpkFieldset-test.js.snap
  packages/bpk-component-form-validation/src/__snapshots__/BpkFormValidation-test.js.snap
  packages/bpk-component-image/src/__snapshots__/BpkBackgroundImage-test.tsx.snap
  packages/bpk-component-image/src/__snapshots__/BpkImage-test.tsx.snap
  packages/bpk-component-input/src/__snapshots__/BpkClearButton-test.tsx.snap
  packages/bpk-component-loading-button/src/__snapshots__/BpkLoadingButton-test.js.snap
  packages/bpk-component-modal/src/BpkModalV2/__snapshots__/BpKModal-test.tsx.snap
  packages/bpk-component-modal/src/__snapshots__/BpkModal-test.tsx.snap
  packages/bpk-component-modal/src/__snapshots__/BpkModalInner-test.tsx.snap
  packages/bpk-component-nudger-row/src/__snapshots__/BpkNudgerRow-test.tsx.snap
  packages/bpk-component-nudger/src/__snapshots__/BpkNudger-test.tsx.snap
  packages/bpk-component-page-indicator/src/__snapshots__/BpkPageIndicator-test.js.snap
  packages/bpk-component-pagination/src/__snapshots__/BpkPaginationNudger-test.js.snap
  packages/bpk-component-popover/src/__snapshots__/BpkPopover-test.js.snap
  packages/bpk-component-section-list/src/__snapshots__/BpkSectionListItem-test.js.snap
  packages/bpk-component-spinner/src/__snapshots__/BpkExtraLargeSpinner-test.js.snap
  packages/bpk-component-spinner/src/__snapshots__/BpkLargeSpinner-test.js.snap
  packages/bpk-component-spinner/src/__snapshots__/BpkSpinner-test.js.snap
  packages/bpk-component-star-rating/src/__snapshots__/BpkInteractiveStar-test.js.snap
  packages/bpk-component-star-rating/src/__snapshots__/BpkInteractiveStarRating-test.js.snap
  packages/bpk-component-star-rating/src/__snapshots__/BpkStar-test.js.snap
  packages/bpk-component-star-rating/src/__snapshots__/BpkStarRating-test.js.snap
  packages/bpk-component-star-rating/src/__snapshots__/withInteractiveStarRatingState-test.js.snap
  packages/package-lock.json
  packages/package.json
Labels: major

#2958 [NO JIRA]: Revert @storybook/addon-docs
  package-lock.json
  package.json
Labels: skip-changelog

#2960 [NO JIRA] Snap drag enabled in slider
  packages/bpk-component-slider/index.ts
  packages/bpk-component-slider/src/BpkSlider-test.tsx
  packages/bpk-component-slider/src/BpkSlider.tsx
  packages/bpk-component-slider/src/__snapshots__/BpkSlider-test.tsx.snap
  packages/bpk-component-slider/src/accessibility-test.tsx
  packages/bpk-component-slider/src/themeAttributes-test.ts
  packages/bpk-component-slider/src/themeAttributes.ts
Labels: major

#2967 [KOA-6248] Add optional label to nudger component
  README.md
  examples/bpk-component-nudger-row/examples.tsx
  examples/bpk-component-nudger-row/stories.ts
  examples/bpk-component-nudger/examples.js
  examples/bpk-component-nudger/stories.js
  packages/bpk-component-infinite-scroll/src/intersection-observer.js
  packages/bpk-component-infinite-scroll/src/withInfiniteScroll-test.js
  packages/bpk-component-nudger-row/README.md
  packages/bpk-component-nudger-row/index.d.ts
  packages/bpk-component-nudger-row/index.ts
  packages/bpk-component-nudger-row/src/BpkNudgerRow-test.tsx
  packages/bpk-component-nudger-row/src/BpkNudgerRow.d.ts
  packages/bpk-component-nudger-row/src/BpkNudgerRow.module.css
  packages/bpk-component-nudger-row/src/BpkNudgerRow.module.scss
  packages/bpk-component-nudger-row/src/BpkNudgerRow.tsx
  packages/bpk-component-nudger-row/src/__snapshots__/BpkNudgerRow-test.tsx.snap
  packages/bpk-component-nudger-row/src/accessibility-test.tsx
  packages/bpk-component-nudger/README.md
  packages/bpk-component-nudger/src/BpkNudger.d.ts
  packages/bpk-component-nudger/src/BpkNudger.module.css
  packages/bpk-component-nudger/src/BpkNudger.module.scss
  packages/bpk-component-nudger/src/BpkNudger.tsx
  packages/bpk-component-nudger/src/__snapshots__/BpkNudger-test.tsx.snap
  packages/bpk-component-nudger/src/common-types.d.ts
  packages/bpk-component-nudger/src/common-types.ts
  packages/bpk-mixins/sass-functions.js
  packages/bpk-react-utils/src/Portal.tsx
  packages/bpk-react-utils/src/deprecated.js
  packages/bpk-stylesheets/index.js
Labels: major

#2969 [KOA-6237] Enable dynamic type for map markers
  packages/bpk-component-map/src/BpkIconMarker.module.css
  packages/bpk-component-map/src/BpkIconMarker.module.scss
  packages/bpk-component-map/src/BpkPriceMarker.module.css
  packages/bpk-component-map/src/BpkPriceMarker.module.scss
Labels: patch

#2968 [NO JIRA] Bump module-resolver and remove css-modules-transform from deps
  babel.config.js
  package-lock.json
  package.json
Labels: dependencies

#2974 [NO JIRA] No jira update guidelines
  CONTRIBUTING.md
Labels: skip-changelog

#2961 [NO JIRA] Add leadingClassName to BpkPrice
  packages/bpk-component-price/README.md
  packages/bpk-component-price/src/BpkPrice-test.js
  packages/bpk-component-price/src/BpkPrice.js
  packages/bpk-component-price/src/__snapshots__/BpkPrice-test.js.snap
Labels: minor

#2975 Correct README.md instructions
  packages/bpk-stylesheets/README.md
Labels: skip-changelog

#2981 [KOA-6262]: Updated explore icon
  package-lock.json
  package.json
  packages/package-lock.json
  packages/package.json
Labels: patch

#2982 [CAPY-119] Update BpkCalendarGrid selection color to surface-subtle
  packages/bpk-component-calendar/src/BpkCalendarDate.module.css
  packages/bpk-component-calendar/src/BpkCalendarDate.module.scss
  packages/bpk-component-calendar/src/BpkCalendarGrid.module.css
  packages/bpk-component-calendar/src/BpkCalendarGrid.module.scss
Labels: major
