Repository Skyscanner/backpack, pull requests merged in 2023-04, with the labels that each got.

#2795 [KOA-5926]: Update BpkNavigationBar to align with Figma
  .storybook/__image_snapshots__/storyshots-test-js-visual-tests-bpk-component-navigation-bar-visual-test-1-snap.png
  examples/bpk-component-navigation-bar/AirlineLogo.js
  examples/bpk-component-navigation-bar/AirlineLogo.module.scss
  packages/bpk-component-navigation-bar/src/BpkNavigationBar.module.scss
  packages/bpk-component-navigation-bar/src/BpkNavigationBarButtonLink.module.scss
  packages/bpk-component-navigation-bar/src/BpkNavigationBarIconButton.module.scss
Labels: minor

#2794 [KOA-5932][Phase 2]: Introduce build caching for visual tests and storybook deploy
  .github/workflows/_build.yml
  .github/workflows/main.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
Labels: skip-changelog

#2801 LOOM-631: Add forwardRef to BpkLink
  packages/bpk-component-link/README.md
  packages/bpk-component-link/src/BpkLink-test.js
  packages/bpk-component-link/src/BpkLink.js
Labels: minor

#2743 [LOOM-640] - setting up Percy for Backpack GitHub actions
  .github/workflows/_build.yml
  .github/workflows/main.yml
  .github/workflows/pr.yml
  package-lock.json
  package.json
Labels: skip-changelog

#2814 [NO-JIRA] Fix chip prop type warning
  packages/bpk-component-chip/src/commonTypes.js
Labels: patch

#2817 [NO JIRA]: Update release process to ship transpiled
  .github/workflows/release.yml
Labels: skip-changelog

#2811 [KOA-5970] Add experimentation guidelines
  CONTRIBUTING.md
Labels: skip-changelog

#2818 [KOA-5987] Fix floating notification alignment
  packages/bpk-component-floating-notification/src/BpkFloatingNotification.module.scss
Labels: patch

#2826 [NO JIRA] Change date in calendar tests
  examples/bpk-component-calendar/examples.js
  examples/bpk-component-input/examples.js
  examples/bpk-component-scrollable-calendar/examples.js
  packages/bpk-component-calendar/README.md
Labels: skip-changelog

#2819 [KOA-5198]: Migrate graphic promo to TS
  .eslintrc
  packages/bpk-component-graphic-promotion/index.d.ts
  packages/bpk-component-graphic-promotion/index.ts
  packages/bpk-component-graphic-promotion/src/BpkGraphicPromo-test.tsx
  packages/bpk-component-graphic-promotion/src/BpkGraphicPromo.d.ts
  packages/bpk-component-graphic-promotion/src/BpkGraphicPromo.tsx
  packages/bpk-component-graphic-promotion/src/__snapshots__/BpkGraphicPromo-test.tsx.snap
  packages/bpk-component-graphic-promotion/src/accessibility-test.tsx
Labels: minor

#2824 [NO JIRA]: Ensure TS is included in transpiled package
  babel.config.js
  package-lock.json
  package.json
  scripts/transpilation/copy-types.js
Labels: skip-changelog

#2825 [KOA-5175] Migrate badge component to TS
  packages/bpk-component-badge/README.md
  packages/bpk-component-badge/index.d.ts
  packages/bpk-component-badge/index.ts
  packages/bpk-component-badge/src/BpkBadge-test.tsx
  packages/bpk-component-badge/src/BpkBadge.d.ts
  packages/bpk-component-badge/src/BpkBadge.tsx
  packages/bpk-component-badge/src/__snapshots__/BpkBadge-test.tsx.snap
  packages/bpk-component-badge/src/accessibility-test.tsx
  packages/bpk-component-badge/src/themeAttributes-test.tsx
  packages/bpk-component-badge/src/themeAttributes.tsx
Labels: minor

#2828 [KOA-6061]: Update foundations to include new upload icon
  .storybook/__image_snapshots__/storyshots-test-js-visual-tests-bpk-component-icon-visual-test-1-snap.png
  package-lock.json
  package.json
  packages/package-lock.json
  packages/package.json
Labels: minor

#2827 [KOA-5193] Migrate dialog component to TS
  packages/bpk-component-dialog/index.d.ts
  packages/bpk-component-dialog/index.ts
  packages/bpk-component-dialog/src/BpkDialog-test.tsx
  packages/bpk-component-dialog/src/BpkDialog.d.ts
  packages/bpk-component-dialog/src/BpkDialog.tsx
  packages/bpk-component-dialog/src/BpkDialogInner.d.ts
  packages/bpk-component-dialog/src/BpkDialogInner.tsx
  packages/bpk-component-dialog/src/__snapshots__/BpkDialog-test.tsx.snap
  packages/bpk-component-dialog/src/accessibility-test.tsx
  packages/bpk-component-dialog/src/common-types.d.ts
  packages/bpk-component-dialog/src/common-types.js
  packages/bpk-component-dialog/src/common-types.ts
Labels: minor
