Repository Skyscanner/backpack, pull requests merged in 2023-09, with the labels that each got.

#2986 [NO JIRA]: Correct icon type props
  packages/bpk-component-icon/src/classNameModifierHOCFactory.d.ts
  packages/bpk-component-icon/src/classNameModifierHOCFactory.tsx
  packages/bpk-component-icon/src/withAlignment.d.ts
  packages/bpk-component-icon/src/withAlignment.tsx
  packages/bpk-component-icon/src/withDescription.d.ts
  packages/bpk-component-icon/src/withDescription.tsx
  packages/bpk-component-icon/src/withRtlSupport.d.ts
Labels: patch

#2994 [No Jira] Fix a11y issue for BpkSelectableChip
  packages/bpk-component-chip/README.md
  packages/bpk-component-chip/src/BpkSelectableChip.tsx
  packages/bpk-component-chip/src/accessibility-test.tsx
Labels: patch

#2988 [KOA-6230] Datatable uses rem values
  examples/bpk-component-datatable/examples.js
  packages/bpk-component-datatable/README.md
  packages/bpk-component-datatable/src/BpkDataTable-test.js
  packages/bpk-component-datatable/src/BpkDataTable.js
  packages/bpk-component-datatable/src/__snapshots__/BpkDataTable-test.js.snap
  packages/bpk-component-datatable/src/accessibility-test.js
  packages/bpk-component-datatable/src/common-types.js
  packages/bpk-component-datatable/src/utils.js
Labels: minor

#2995 [NO JIRA]: Correct types for datepicker and dialog
  packages/bpk-component-datepicker/src/BpkDatepicker.d.ts
  packages/bpk-component-datepicker/src/BpkDatepicker.tsx
  packages/bpk-component-dialog/README.md
  packages/bpk-component-dialog/src/BpkDialog.tsx
  packages/bpk-component-dialog/src/common-types.d.ts
  packages/bpk-component-dialog/src/common-types.ts
Labels: patch

#2998 [KOA-6198]: Fix iPad detection utility for newer generation devices
  packages/bpk-react-utils/src/deviceDetection-test.ts
  packages/bpk-react-utils/src/deviceDetection.ts
Labels: patch

#2997 [BD-7264] Add new component - BpkSaveButton
  README.md
  examples/bpk-component-card-button/examples.tsx
  examples/bpk-component-card-button/stories.ts
  package-lock.json
  package.json
  packages/bpk-component-card-button/README.md
  packages/bpk-component-card-button/index.ts
  packages/bpk-component-card-button/src/BpkSaveButton-test.tsx
  packages/bpk-component-card-button/src/BpkSaveButton.d.ts
  packages/bpk-component-card-button/src/BpkSaveButton.module.css
  packages/bpk-component-card-button/src/BpkSaveButton.module.scss
  packages/bpk-component-card-button/src/BpkSaveButton.tsx
  packages/bpk-component-card-button/src/__snapshots__/BpkSaveButton-test.tsx.snap
  packages/bpk-component-card-button/src/accessibility-test.tsx
  packages/package-lock.json
  packages/package.json
Labels: minor

#3007 [BD-7310][BpkMap] Add a BpkPriceMarkerV2 component
  examples/bpk-component-map/examples.js
  examples/bpk-component-map/examples.module.css
  examples/bpk-component-map/stories.js
  package-lock.json
  package.json
  packages/bpk-component-map/README.md
  packages/bpk-component-map/index.js
  packages/bpk-component-map/src/BpkBasicMapMarker.d.ts
  packages/bpk-component-map/src/BpkPriceMarkerV2/BpkPriceMarker-test.tsx
  packages/bpk-component-map/src/BpkPriceMarkerV2/BpkPriceMarker.d.ts
  packages/bpk-component-map/src/BpkPriceMarkerV2/BpkPriceMarker.module.css
  packages/bpk-component-map/src/BpkPriceMarkerV2/BpkPriceMarker.module.scss
  packages/bpk-component-map/src/BpkPriceMarkerV2/BpkPriceMarker.tsx
  packages/bpk-component-map/src/BpkPriceMarkerV2/__snapshots__/BpkPriceMarker-test.tsx.snap
  packages/bpk-component-map/src/BpkPriceMarkerV2/accessibility-test.tsx
  packages/package-lock.json
  packages/package.json
Labels: minor

#3000 [NO JIRA] Add warnings and comments for old data table API
  dangerfile.ts
  examples/bpk-component-datatable/examples.js
  examples/bpk-component-datatable/stories.js
  packages/bpk-component-datatable/README.md
  packages/bpk-component-datatable/docs/migrating.md
  packages/bpk-component-datatable/src/BpkDataTable-test.js
  packages/bpk-component-datatable/src/BpkDataTable.js
  packages/bpk-component-datatable/src/BpkDataTableColumn.js
  packages/bpk-component-datatable/src/utils.js
Labels: patch

#3011 [KOA-6046] Add automatic API tables for components that export multiple components
  .storybook/main.ts
  .storybook/preview.tsx
  .storybook/webpack.config.js
  examples/bpk-component-accordion/stories.js
  examples/bpk-component-banner-alert/stories.js
  examples/bpk-component-breadcrumb/stories.js
  examples/bpk-component-calendar/stories.js
  examples/bpk-component-card/stories.js
  examples/bpk-component-chip/stories.js
  examples/bpk-component-datatable/stories.js
  examples/bpk-component-description-list/stories.js
  examples/bpk-component-flare/stories.js
  examples/bpk-component-horizontal-nav/stories.js
  examples/bpk-component-image/stories.js
  examples/bpk-component-input/stories.js
  examples/bpk-component-link/stories.js
  examples/bpk-component-list/stories.js
  examples/bpk-component-map/stories.js
  examples/bpk-component-navigation-bar/stories.js
  examples/bpk-component-nudger/stories.js
  examples/bpk-component-overlay/stories.tsx
  examples/bpk-component-section-list/stories.js
  examples/bpk-component-spinner/stories.js
  examples/bpk-component-star-rating/stories.js
  examples/bpk-component-table/stories.js
  packages/bpk-component-boilerplate/src/BpkBoilerplate-test.tsx
  packages/bpk-component-boilerplate/src/accessibility-test.tsx
  packages/bpk-component-calendar/DOCS.md
  packages/bpk-component-card/src/BpkCard.tsx
  packages/bpk-component-card/src/BpkDividedCard.tsx
  packages/bpk-component-dialog/src/BpkDialog.tsx
  packages/bpk-component-input/src/BpkClearButton-test.tsx
  packages/bpk-component-input/src/BpkClearButton.tsx
  packages/bpk-component-input/src/BpkInput.tsx
  packages/bpk-component-overlay/index.d.ts
  packages/bpk-component-overlay/index.ts
  packages/bpk-component-overlay/src/accessibility-test.tsx
  packages/bpk-component-tooltip/src/BpkTooltip.tsx
  packages/bpk-component-tooltip/src/BpkTooltipPortal.tsx
Labels: skip-changelog

#3012 [KOA-6290][BpkSlider]: Bump react-slider to solve snap back issue
  packages/bpk-component-slider/src/BpkSlider-test.tsx
  packages/bpk-component-slider/src/__snapshots__/BpkSlider-test.tsx.snap
  packages/bpk-component-slider/src/accessibility-test.tsx
  packages/package-lock.json
  packages/package.json
Labels: patch

#3018 [NO JIRA]: New Skyscanner Focus Indicator
  package-lock.json
  packages/bpk-component-button/src/BpkButtonLink.module.css
  packages/bpk-component-button/src/BpkButtonLinkOnDark.module.css
  packages/bpk-component-button/src/BpkButtonV2/BpkButton.module.css
  packages/bpk-mixins/src/mixins/_buttons.scss
  packages/bpk-mixins/src/mixins/_utils.scss
  packages/bpk-stylesheets/base.css
  packages/bpk-stylesheets/index.scss
Labels: minor

#3017 [KOA-6296] Add Storybook API tables for HOCs
  examples/bpk-component-accordion/stories-utils.js
  examples/bpk-component-accordion/stories.js
  examples/bpk-component-banner-alert/stories-utils.tsx
  examples/bpk-component-banner-alert/stories.js
  examples/bpk-component-calendar/stories-utils.tsx
  examples/bpk-component-calendar/stories.js
  examples/bpk-component-input/stories-utils.tsx
  examples/bpk-component-input/stories.js
  examples/bpk-component-map/stories-utils.js
  examples/bpk-component-map/stories.js
  examples/bpk-component-star-rating/stories-utils.js
  examples/bpk-component-star-rating/stories.js
  packages/bpk-component-banner-alert/src/withBannerAlertState.d.ts
  packages/bpk-component-banner-alert/src/withBannerAlertState.tsx
  packages/bpk-component-calendar/index.d.ts
  packages/bpk-component-calendar/src/BpkCalendarContainer.d.ts
  packages/bpk-component-calendar/src/BpkCalendarContainer.tsx
  packages/bpk-component-calendar/src/composeCalendar.d.ts
  packages/bpk-component-calendar/src/composeCalendar.tsx
  packages/bpk-component-horizontal-nav/src/BpkHorizontalNav.js
  packages/bpk-component-horizontal-nav/src/BpkHorizontalNavItem.js
  packages/bpk-component-input/src/withOpenEvents.d.ts
  packages/bpk-component-input/src/withOpenEvents.tsx
  packages/bpk-component-popover/src/BpkPopoverPortal.js
Labels: patch
