Repository Skyscanner/backpack, pull requests merged in 2023-07, with the labels that each got.

#2898 [KOA-6134] Update react-responsive
  packages/bpk-component-breakpoint/src/BpkBreakpoint.tsx
  packages/package-lock.json
  packages/package.json
Labels: minor

#2901 [KOA-5703]: Bump css-loader and postcss-loader
  .storybook/webpack.config.js
  package-lock.json
  package.json
Labels: skip-changelog

#2905 [NO JIRA] Fix dialog types
  packages/bpk-component-dialog/src/BpkDialogInner.d.ts
  packages/bpk-component-dialog/src/common-types.d.ts
  packages/bpk-component-dialog/src/common-types.ts
Labels: patch

#2909 [KOA-6039] Upgrade to jest v29
  package-lock.json
  package.json
  packages/bpk-component-infinite-scroll/src/withInfiniteScroll-test.js
  packages/bpk-component-modal/src/BpkModalV2/BpKModal-test.tsx
  packages/bpk-react-utils/src/Portal-test.tsx
Labels: skip-changelog

#2913 [KOA-6040] Bump autoprefixer
  package-lock.json
  package.json
Labels: skip-changelog

#2912 [BD-7115] Add Section Header into Backpack
  README.md
  examples/bpk-component-section-header/examples.module.scss
  examples/bpk-component-section-header/examples.tsx
  examples/bpk-component-section-header/stories.ts
  packages/bpk-component-section-header/README.md
  packages/bpk-component-section-header/index.ts
  packages/bpk-component-section-header/src/BpkSectionHeader-test.tsx
  packages/bpk-component-section-header/src/BpkSectionHeader.d.ts
  packages/bpk-component-section-header/src/BpkSectionHeader.module.scss
  packages/bpk-component-section-header/src/BpkSectionHeader.tsx
  packages/bpk-component-section-header/src/__snapshots__/BpkSectionHeader-test.tsx.snap
  packages/bpk-component-section-header/src/accessibility-test.tsx
Labels: minor

#2919 [KOA-6041] Bump webpack to v5
  .storybook/main.js
  package-lock.json
  package.json
Labels: skip-changelog

#2928 [KOA-6212] Update card wrapper example to match Figma
  examples/bpk-component-card/examples.js
Labels: skip-changelog

#2927 [KOA-6216] Add AI icon
  package-lock.json
  package.json
  packages/package-lock.json
  packages/package.json
Labels: minor

#2925 SHIBA-1620 Add RTL to BpkCalendarGrid date range
  packages/bpk-component-calendar/src/BpkCalendarGrid.module.scss
Labels: minor

#2899 [KOA-6135] Update contribution guidelines
  CONTRIBUTING.md
  packages/bpk-component-boilerplate/src/BpkBoilerplate.tsx
Labels: skip-changelog

#2935 Change imports for breakpoints into bpk-component-breakpoint
  .storybook/preview.js
  packages/bpk-component-breakpoint/src/BpkBreakpoint.tsx
Labels: patch
