Repository Skyscanner/backpack, pull requests merged in 2023-03, with the labels that each got.

#2774 [KOA-5942]: Remove old release process
  .jirabot.yml
  CODE_REVIEW_GUIDELINES.md
  README.md
  meta.json
  package-lock.json
  package.json
  packages/README.md
  scripts/npm/check-owners.js
  scripts/npm/get-owners.js
  scripts/npm/remove-owner.sh
  scripts/npm/update-owners.sh
  scripts/publish-process/single-package/release.js
  scripts/publish-process/single-package/shell.js
  scripts/publish-process/transform-js-scss-css-imports.js
  scripts/publish-process/update-changelog.js
  scripts/video/convert-to-mp4.sh
Labels: skip-changelog

#2775 [NO JIRA]: Update config for running dependabot changes
  .github/dependabot.yml
  .github/workflows/pr.yml
Labels: skip-changelog

#2782 [KOA-5931]: Add missing supernova dependency
  package-lock.json
  package.json
Labels: skip-changelog

#2778 [KOA-5922] Update slider design and remove large variant
  .storybook/__image_snapshots__/storyshots-test-js-visual-tests-bpk-component-slider-visual-test-1-snap.png
  examples/bpk-component-slider/examples.js
  examples/bpk-component-slider/stories.js
  package-lock.json
  package.json
  packages/bpk-component-slider/README.md
  packages/bpk-component-slider/src/BpkSlider-test.js
  packages/bpk-component-slider/src/BpkSlider.js
  packages/bpk-component-slider/src/BpkSlider.module.scss
  packages/bpk-component-slider/src/__snapshots__/BpkSlider-test.js.snap
  packages/package-lock.json
  packages/package.json
Labels: major

#2783 Koa 5931 update supernova step
  .github/workflows/release.yml
Labels: skip-changelog

#2779 [BPKR-250]: Change overlay image
  .storybook/__image_snapshots__/storyshots-test-js-visual-tests-bpk-component-overlay-visual-test-1-snap.png
  examples/bpk-component-overlay/examples.js
Labels: skip-changelog

#2786 [KOA-5992] Update baggage icons
  package-lock.json
  package.json
  packages/package-lock.json
  packages/package.json
Labels: minor

#2785 [LOOM-614]: bpk accordion updates
  .storybook/__image_snapshots__/storyshots-test-js-visual-tests-bpk-component-accordion-visual-test-on-dark-1-snap.png
  examples/bpk-component-accordion/examples.js
  examples/bpk-component-accordion/stories.js
  packages/bpk-component-accordion/README.md
  packages/bpk-component-accordion/src/BpkAccordion.js
  packages/bpk-component-accordion/src/BpkAccordion.module.scss
  packages/bpk-component-accordion/src/BpkAccordionItem-test.js
  packages/bpk-component-accordion/src/BpkAccordionItem.js
  packages/bpk-component-accordion/src/BpkAccordionItem.module.scss
  packages/bpk-component-accordion/src/__snapshots__/BpkAccordionItem-test.js.snap
  packages/bpk-component-accordion/src/__snapshots__/withAccordionItemState-test.js.snap
Labels: minor

#2789 [LOOM-614]: bpk accordion divider api
  examples/bpk-component-accordion/examples.js
  examples/bpk-component-accordion/stories.js
  packages/bpk-component-accordion/README.md
  packages/bpk-component-accordion/src/BpkAccordion.js
  packages/bpk-component-accordion/src/BpkAccordionItem-test.js
  packages/bpk-component-accordion/src/BpkAccordionItem.js
  packages/bpk-component-accordion/src/__snapshots__/BpkAccordionItem-test.js.snap
Labels: minor
