Repository Skyscanner/backpack, pull requests merged in 2023-10, with the labels that each got.

#3024 [LUNA-621] RTL support for BpkFloatingNotification
  packages/bpk-component-floating-notification/src/BpkFloatingNotification.module.css
  packages/bpk-component-floating-notification/src/BpkFloatingNotification.module.scss
Labels: patch

#3022 [KOA-6249] Add automated visual tests with zoom enabled
  .storybook/preview.tsx
  examples/bpk-component-accordion/stories.js
  examples/bpk-component-badge/stories.js
  examples/bpk-component-banner-alert/stories.js
  examples/bpk-component-barchart/stories.js
  examples/bpk-component-blockquote/stories.js
  examples/bpk-component-breadcrumb/stories.js
  examples/bpk-component-button/stories.js
  examples/bpk-component-calendar/stories.js
  examples/bpk-component-card-button/stories.ts
  examples/bpk-component-card/stories.js
  examples/bpk-component-checkbox/stories.js
  examples/bpk-component-chip/stories.js
  examples/bpk-component-close-button/stories.js
  examples/bpk-component-code/stories.js
  examples/bpk-component-datatable/stories.js
  examples/bpk-component-datepicker/stories.js
  examples/bpk-component-description-list/stories.js
  examples/bpk-component-fieldset/stories.js
  examples/bpk-component-flare/stories.js
  examples/bpk-component-floating-notification/stories.js
  examples/bpk-component-form-validation/stories.js
  examples/bpk-component-graphic-promotion/stories.js
  examples/bpk-component-horizontal-nav/stories.js
  examples/bpk-component-icon/stories.js
  examples/bpk-component-input/stories.js
  examples/bpk-component-label/stories.js
  examples/bpk-component-link/stories.js
  examples/bpk-component-list/stories.js
  examples/bpk-component-loading-button/stories.js
  examples/bpk-component-navigation-bar/stories.js
  examples/bpk-component-nudger/stories.js
  examples/bpk-component-overlay/stories.tsx
  examples/bpk-component-page-indicator/stories.js
  examples/bpk-component-pagination/stories.js
  examples/bpk-component-panel/stories.js
  examples/bpk-component-phone-input/stories.js
  examples/bpk-component-price/stories.js
  examples/bpk-component-progress/stories.js
  examples/bpk-component-radio/stories.js
  examples/bpk-component-rating/stories.js
  examples/bpk-component-scrollable-calendar/stories.js
  examples/bpk-component-section-header/stories.ts
  examples/bpk-component-section-list/stories.js
  examples/bpk-component-select/stories.js
  examples/bpk-component-slider/stories.js
  examples/bpk-component-split-input/stories.js
  examples/bpk-component-star-rating/stories.js
  examples/bpk-component-switch/stories.js
  examples/bpk-component-text/stories.js
  examples/bpk-component-textarea/stories.js
  examples/bpk-component-ticket/stories.js
  packages/bpk-animate-height/README.md
Labels: skip-changelog

#3027 [NO JIRA] Fix popover type export
  packages/bpk-component-popover/src/BpkPopoverPortal.js
Labels: patch

#3021 [NO-JIRA] Update BkpModalV2
  packages/bpk-component-modal/src/BpkModalV2/BpKModal.module.css
  packages/bpk-component-modal/src/BpkModalV2/BpKModal.module.scss
  packages/bpk-component-modal/src/BpkModalV2/BpkModal.tsx
Labels: minor

#3034 [NO JIRA] Fix button onClick handler type
  packages/bpk-component-button/src/BpkButtonV2/common-types.d.ts
  packages/bpk-component-button/src/BpkButtonV2/common-types.tsx
Labels: patch

#3035 [LUNA-829] Fix css for FloatingNotification CTA message
  packages/bpk-component-floating-notification/src/BpkFloatingNotification.module.css
  packages/bpk-component-floating-notification/src/BpkFloatingNotification.module.scss
Labels: patch

#3036 [NO JIRA]: Upgrade internally to BpkButtonV2
  packages/bpk-component-floating-notification/src/BpkFloatingNotification.js
  packages/bpk-component-floating-notification/src/__snapshots__/BpkFloatingNotification-test.js.snap
  packages/bpk-component-page-indicator/src/NavButton.js
  packages/bpk-component-pagination/src/BpkPaginationNudger.js
  packages/bpk-component-pagination/src/BpkPaginationPage.js
Labels: patch

#3028 [BD-7321][BpkMap] change icon marker style(color)
  examples/bpk-component-map/examples.js
  packages/bpk-component-map/README.md
  packages/bpk-component-map/src/BpkIconMarker-test.js
  packages/bpk-component-map/src/BpkIconMarker.js
  packages/bpk-component-map/src/BpkIconMarker.module.css
  packages/bpk-component-map/src/BpkIconMarker.module.scss
  packages/bpk-component-map/src/BpkIconMarkerBackground.module.css
  packages/bpk-component-map/src/BpkIconMarkerBackground.module.scss
  packages/bpk-component-map/src/__snapshots__/BpkIconMarker-test.js.snap
Labels: minor

#3040 [LUNA-874] Update react-transition-group
  packages/bpk-component-floating-notification/src/BpkFloatingNotification.js
  packages/package-lock.json
  packages/package.json
Labels: major

#3045 [ARGG-811]: Replaces Scss icons in Backpack
  packages/bpk-mixins/src/mixins/_forms.scss
  packages/bpk-mixins/src/mixins/_svgs.scss
Labels: patch

#3046 [NOJIRA] Export TS types for Section Header Component
  packages/bpk-component-section-header/index.d.ts
Labels: patch

#3048 [ARGG-812]: Remove svg imports and icon functions
  package-lock.json
  package.json
  packages/bpk-mixins/src/mixins/_svgs.scss
  packages/package-lock.json
  packages/package.json
Labels: major

#3049 [NO-JIRA] Fix Bug on dialog with open attribute for BpkModalV2
  packages/bpk-component-modal/src/BpkModalV2/BpkModal.tsx
Labels: minor
