Repository Skyscanner/backpack, pull requests merged in 2023-06, with the labels that each got.

#2868 [KOA-6118] Migrate text component to TS
  packages/bpk-component-chip/src/BpkSelectableChip.tsx
  packages/bpk-component-graphic-promotion/src/BpkGraphicPromo.tsx
  packages/bpk-component-modal/src/BpkModalV2/BpkModal.tsx
  packages/bpk-component-text/README.md
  packages/bpk-component-text/docs/replacing-weight-and-bold-props.md
  packages/bpk-component-text/index.d.ts
  packages/bpk-component-text/index.ts
  packages/bpk-component-text/src/BpkText-test.js
  packages/bpk-component-text/src/BpkText-test.tsx
  packages/bpk-component-text/src/BpkText.d.ts
  packages/bpk-component-text/src/BpkText.js
  packages/bpk-component-text/src/BpkText.module.scss
  packages/bpk-component-text/src/BpkText.tsx
  packages/bpk-component-text/src/__snapshots__/BpkText-test.tsx.snap
  packages/bpk-component-text/src/accessibility-test.tsx
Labels: minor

#2865 [KOA-6124] Migrate tooltip to TS
  packages/bpk-component-tooltip/index.d.ts
  packages/bpk-component-tooltip/index.ts
  packages/bpk-component-tooltip/src/BpkTooltip-test.tsx
  packages/bpk-component-tooltip/src/BpkTooltip.d.ts
  packages/bpk-component-tooltip/src/BpkTooltip.tsx
  packages/bpk-component-tooltip/src/BpkTooltipPortal-test.tsx
  packages/bpk-component-tooltip/src/BpkTooltipPortal.d.ts
  packages/bpk-component-tooltip/src/BpkTooltipPortal.tsx
  packages/bpk-component-tooltip/src/__snapshots__/BpkTooltip-test.tsx.snap
  packages/bpk-component-tooltip/src/__snapshots__/BpkTooltipPortal-test.tsx.snap
  packages/bpk-component-tooltip/src/accessibility-test.tsx
  packages/bpk-component-tooltip/src/constants.d.ts
  packages/bpk-component-tooltip/src/constants.ts
  packages/bpk-react-utils/src/Portal.tsx
Labels: minor

#2864 [KOA-6138] Fix calendar hoc types and re-enable test
  packages/bpk-component-calendar/src/BpkCalendarContainer-test.tsx
  packages/bpk-component-calendar/src/BpkCalendarContainer.d.ts
  packages/bpk-component-calendar/src/BpkCalendarContainer.tsx
  packages/bpk-component-calendar/src/accessibility-test.tsx
  packages/bpk-component-calendar/src/composeCalendar.d.ts
  packages/bpk-component-calendar/src/composeCalendar.tsx
Labels: patch

#2869 [NO-JIRA] Update BpkModalV2
  examples/bpk-component-modal-v2/examples.tsx
  examples/bpk-component-modal-v2/stories.tsx
  packages/bpk-component-modal/src/BpkModalV2/BpKModal-test.tsx
  packages/bpk-component-modal/src/BpkModalV2/BpKModal.module.scss
  packages/bpk-component-modal/src/BpkModalV2/BpkModal.d.ts
  packages/bpk-component-modal/src/BpkModalV2/BpkModal.tsx
  packages/bpk-component-modal/src/BpkModalV2/README.md
  packages/bpk-component-modal/src/BpkModalV2/__snapshots__/BpKModal-test.tsx.snap
Labels: minor

#2874 [NO JIRA] Fix modal props
  packages/bpk-component-modal/README.md
  packages/bpk-component-modal/src/BpkModal.d.ts
  packages/bpk-component-modal/src/BpkModal.tsx
  packages/bpk-component-modal/src/BpkModalInner.d.ts
  packages/bpk-component-modal/src/BpkModalInner.tsx
  packages/bpk-component-modal/src/__snapshots__/BpkModal-test.tsx.snap
  packages/bpk-scrim-utils/index.d.ts
  packages/bpk-scrim-utils/src/withScrim.d.ts
  packages/bpk-scrim-utils/src/withScrim.tsx
Labels: patch

#2863 [NEUT-1089] update bpk overlay component
  .storybook/__image_snapshots__/storyshots-test-js-visual-tests-bpk-component-overlay-visual-test-1-snap.png
  examples/bpk-component-overlay/examples.js
  examples/bpk-component-overlay/stories.tsx
  packages/bpk-component-overlay/README.md
  packages/bpk-component-overlay/index.d.ts
  packages/bpk-component-overlay/index.ts
  packages/bpk-component-overlay/src/BpkOverlay-test.tsx
  packages/bpk-component-overlay/src/BpkOverlay.d.ts
  packages/bpk-component-overlay/src/BpkOverlay.js
  packages/bpk-component-overlay/src/BpkOverlay.tsx
  packages/bpk-component-overlay/src/__snapshots__/BpkOverlay-test.tsx.snap
  packages/bpk-component-overlay/src/accessibility-test.tsx
Labels: major

#2884 [NO JIRA] Update decisions
  decisions/adding-types.md
  decisions/flowfixme.md
  decisions/ignoring.md
  decisions/ts-deprecating-props.md
  decisions/versioning-rules.md
Labels: skip-changelog

#2877 [No-JIRA] Add animation when opening BpkModalV2
  packages/bpk-component-modal/src/BpkModalV2/BpKModal.module.scss
  packages/bpk-component-modal/src/BpkModalV2/BpkModal.tsx
Labels: minor

#2889 [KOA-6076] Upgrade Backpack to Node 18
  .naverc
  .nvmrc
  CONTRIBUTING.md
  package-lock.json
  package.json
Labels: skip-changelog

#2883 [NO JIRA] Update PR template
  .github/pull_request_template.md
Labels: skip-changelog

#2893 [NO JIRA]: Updating dependencies
  package-lock.json
  package.json
  packages/package-lock.json
  packages/package.json
Labels: patch

#2885 [NEUT-1361] Fix Card Wrapper Header Cursor and Click Effect Styling
  packages/bpk-component-card/src/BpkCardWrapper.module.scss
Labels: minor

#2892 [LOOM-772]: remove the display.none fix - replace with existing scroll fixes
  packages/bpk-scrim-utils/src/withScrim-test.tsx
  packages/bpk-scrim-utils/src/withScrim.tsx
Labels: patch

#2894 [KOA-6133] Add new breakpoints and migrate to TS
  examples/bpk-component-breakpoint/examples.js
  package-lock.json
  package.json
  packages/bpk-component-breakpoint/index.d.ts
  packages/bpk-component-breakpoint/index.ts
  packages/bpk-component-breakpoint/src/BpkBreakpoint-test.tsx
  packages/bpk-component-breakpoint/src/BpkBreakpoint.d.ts
  packages/bpk-component-breakpoint/src/BpkBreakpoint.tsx
  packages/bpk-component-breakpoint/src/__snapshots__/BpkBreakpoint-test.tsx.snap
  packages/bpk-component-breakpoint/src/accessibility-test.tsx
  packages/package-lock.json
  packages/package.json
Labels: minor

#2882 [KOA-5537] Migrate image to TS
  packages/bpk-component-image/README.md
  packages/bpk-component-image/index.d.ts
  packages/bpk-component-image/index.ts
  packages/bpk-component-image/src/BpkBackgroundImage-test.tsx
  packages/bpk-component-image/src/BpkBackgroundImage.d.ts
  packages/bpk-component-image/src/BpkBackgroundImage.tsx
  packages/bpk-component-image/src/BpkImage-test.tsx
  packages/bpk-component-image/src/BpkImage.d.ts
  packages/bpk-component-image/src/BpkImage.tsx
  packages/bpk-component-image/src/BpkImageBorderRadiusStyles.d.ts
  packages/bpk-component-image/src/BpkImageBorderRadiusStyles.ts
  packages/bpk-component-image/src/__snapshots__/BpkBackgroundImage-test.tsx.snap
  packages/bpk-component-image/src/__snapshots__/BpkImage-test.tsx.snap
  packages/bpk-component-image/src/__snapshots__/withLazyLoading-test.tsx.snap
  packages/bpk-component-image/src/accessibility-test.tsx
  packages/bpk-component-image/src/withLazyLoading-test.tsx
  packages/bpk-component-image/src/withLazyLoading.d.ts
  packages/bpk-component-image/src/withLazyLoading.tsx
  packages/bpk-component-image/src/withLoadingBehavior.d.ts
  packages/bpk-component-image/src/withLoadingBehavior.tsx
Labels: minor

#2891 [NO JIRA] Add percy config for debugging
  .percy.yml
Labels: skip-changelog

#2900 [LOOM-796]: Fix scroll behaviour for _non_ iOS devices
  packages/bpk-scrim-utils/src/withScrim-test.tsx
  packages/bpk-scrim-utils/src/withScrim.tsx
Labels: patch
