Repository Skyscanner/backpack, pull requests merged in 2023-11, with the labels that each got.

#3061 Remove Map visual test due to rendering issues
  examples/bpk-component-map/stories.js
Labels: skip-changelog

#3062 LUNA-903 Handle word wrap for Korean language
  packages/bpk-component-floating-notification/src/BpkFloatingNotification.module.css
  packages/bpk-component-floating-notification/src/BpkFloatingNotification.module.scss
Labels: patch

#3060 [ARGG-851] Fix withScrimmedPortal component for deterministic order of execution
  packages/bpk-scrim-utils/README.md
  packages/bpk-scrim-utils/src/__snapshots__/withScrimmedPortal-test.tsx.snap
  packages/bpk-scrim-utils/src/withScrimmedPortal-test.tsx
  packages/bpk-scrim-utils/src/withScrimmedPortal.tsx
Labels: patch

#3069 Disable hover for save button on mweb
  packages/bpk-component-card-button/src/BpkSaveButton.module.css
  packages/bpk-component-card-button/src/BpkSaveButton.module.scss
Labels: patch

#3070 Fix async toggle style issue & BpkButton -> BpkButtonV2 in README files
  examples/bpk-component-card-button/examples.tsx
  examples/bpk-component-card-button/stories.ts
  packages/bpk-component-button/README.md
  packages/bpk-component-card-button/src/BpkSaveButton.tsx
  packages/bpk-component-icon/README.md
Labels: patch

#3057 [SHIBA-2119] Added Optional Height Prop for Scrollable Calendar
  examples/bpk-component-scrollable-calendar/examples.js
  examples/bpk-component-scrollable-calendar/stories.js
  packages/bpk-component-calendar/src/BpkCalendarContainer.d.ts
  packages/bpk-component-calendar/src/BpkCalendarContainer.tsx
  packages/bpk-component-calendar/src/composeCalendar.d.ts
  packages/bpk-component-calendar/src/composeCalendar.tsx
  packages/bpk-component-scrollable-calendar/src/BpkScrollableCalendarGridList-test.tsx
  packages/bpk-component-scrollable-calendar/src/BpkScrollableCalendarGridList.d.ts
  packages/bpk-component-scrollable-calendar/src/BpkScrollableCalendarGridList.tsx
  packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendarGridList-test.tsx.snap
Labels: minor

#3071 Remove dependencies label from label-check
  .github/workflows/label-check.yml
Labels: skip-changelog

#3084 [NO_JIRA]Price marker style adjustment
  packages/bpk-component-map/src/BpkPriceMarkerV2/BpkPriceMarker.module.css
  packages/bpk-component-map/src/BpkPriceMarkerV2/BpkPriceMarker.module.scss
  packages/bpk-component-map/src/BpkPriceMarkerV2/BpkPriceMarker.tsx
  packages/bpk-component-map/src/BpkPriceMarkerV2/__snapshots__/BpkPriceMarker-test.tsx.snap
Labels: patch

#3093 Fix bpk-stylesheets :global transpilation
  packages/bpk-stylesheets/base.css
  packages/bpk-stylesheets/webpack.config.babel.js
Labels: patch

#3092 DTO-4938 prevent wide Modalv2 from going off edge of screen
  packages/bpk-component-modal/src/BpkModalV2/BpKModal.module.css
  packages/bpk-component-modal/src/BpkModalV2/BpKModal.module.scss
Labels: patch
