Repository Skyscanner/backpack, pull requests merged in 2024-03, with the labels that each got.

#3278 LOOM-1262 redundant BkpBannerAlertInner style removed and snapshots updated
  packages/bpk-component-banner-alert/src/BpkBannerAlertInner.tsx
  packages/bpk-component-banner-alert/src/__snapshots__/BpkBannerAlertDismissable-test.tsx.snap
  packages/bpk-component-banner-alert/src/__snapshots__/BpkBannerAlertInner-test.tsx.snap
  packages/bpk-component-banner-alert/src/__snapshots__/withBannerAlertState-test.tsx.snap
Labels: minor

#3273 [DTO-5203] - BpkNavigationBar fix classname issue
  packages/bpk-component-bottom-sheet/src/__snapshots__/BpkBottomSheet-test.tsx.snap
  packages/bpk-component-modal/src/__snapshots__/BpkModal-test.tsx.snap
  packages/bpk-component-modal/src/__snapshots__/BpkModalInner-test.tsx.snap
  packages/bpk-component-navigation-bar/src/BpkNavigationBar.tsx
  packages/bpk-component-navigation-bar/src/__snapshots__/BpkNavigationBar-test.tsx.snap
Labels: patch

#3231 [NO JIRA]: Update NPM cache generation logic
  .github/workflows/_build.yml
  .github/workflows/main.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
Labels: skip-changelog

#3281 [BpkMobileScrollContainer] Add aria label
  packages/bpk-component-mobile-scroll-container/src/BpkMobileScrollContainer-test.js
  packages/bpk-component-mobile-scroll-container/src/BpkMobileScrollContainer.js
  packages/bpk-component-mobile-scroll-container/src/__snapshots__/BpkMobileScrollContainer-test.js.snap
Labels: minor

#3279 [BpkHorizontalNav] Add aria label
  packages/bpk-component-horizontal-nav/src/BpkHorizontalNav-test.js
  packages/bpk-component-horizontal-nav/src/BpkHorizontalNav.js
  packages/bpk-component-horizontal-nav/src/__snapshots__/BpkHorizontalNav-test.js.snap
  packages/bpk-component-horizontal-nav/src/accessibility-test.js
Labels: minor

#3294 ST-5444: Update bpk-svgs from 19.0.1 to 19.1.0
  package-lock.json
  package.json
  packages/package-lock.json
  packages/package.json
Labels: patch

#3295 [NO JIRA]: Fix transpilation scripts to capture nested files
  scripts/transpilation/copy-css.js
  scripts/transpilation/copy-types.js
Labels: patch

#3283 LOOM-1275 BkpCloseButton - Move Icon style override into span
  packages/bpk-component-banner-alert/src/__snapshots__/BpkBannerAlertDismissable-test.tsx.snap
  packages/bpk-component-banner-alert/src/__snapshots__/BpkBannerAlertInner-test.tsx.snap
  packages/bpk-component-banner-alert/src/__snapshots__/withBannerAlertState-test.tsx.snap
  packages/bpk-component-bottom-sheet/src/__snapshots__/BpkBottomSheet-test.tsx.snap
  packages/bpk-component-close-button/src/BpkCloseButton.js
  packages/bpk-component-close-button/src/BpkCloseButton.module.scss
  packages/bpk-component-close-button/src/__snapshots__/BpkCloseButton-test.js.snap
  packages/bpk-component-dialog/src/__snapshots__/BpkDialog-test.tsx.snap
  packages/bpk-component-drawer/src/__snapshots__/BpkDrawer-test.js.snap
  packages/bpk-component-drawer/src/__snapshots__/BpkDrawerContent-test.js.snap
  packages/bpk-component-info-banner/src/__snapshots__/BpkInfoBannerDismissable-test.tsx.snap
  packages/bpk-component-info-banner/src/__snapshots__/BpkInfoBannerInner-test.tsx.snap
  packages/bpk-component-info-banner/src/__snapshots__/withBannerAlertState-test.tsx.snap
  packages/bpk-component-modal/src/BpkModalV2/__snapshots__/BpKModal-test.tsx.snap
  packages/bpk-component-modal/src/__snapshots__/BpkModal-test.tsx.snap
  packages/bpk-component-modal/src/__snapshots__/BpkModalInner-test.tsx.snap
  packages/bpk-component-navigation-bar/src/__snapshots__/BpkNavigationBar-test.tsx.snap
  packages/bpk-component-navigation-bar/src/__snapshots__/BpkNavigationBarIconButton-test.tsx.snap
  packages/bpk-component-popover/src/__snapshots__/BpkPopover-test.js.snap
Labels: minor

#3304 Creating dependabot group patterns to group dependencies for PRs
  .github/dependabot.yml
Labels: skip-changelog

#3296 [ARGG-1057]: Setup dependabot to ignore patch versions
  .github/dependabot.yml
Labels: skip-changelog

#3299 BpkBreakpoint: Fix Server Side Rendering
  packages/bpk-component-bottom-sheet/src/BpkBottomSheet-test.tsx
  packages/bpk-component-bottom-sheet/src/accessibility-test.tsx
  packages/bpk-component-breakpoint/README.md
  packages/bpk-component-breakpoint/index.d.ts
  packages/bpk-component-breakpoint/src/BpkBreakpoint-test.tsx
  packages/bpk-component-breakpoint/src/BpkBreakpoint.tsx
  packages/bpk-component-breakpoint/src/__snapshots__/BpkBreakpoint-test.tsx.snap
  packages/bpk-component-breakpoint/src/__snapshots__/useMediaQuery-test.tsx.snap
  packages/bpk-component-breakpoint/src/accessibility-test.tsx
  packages/bpk-component-breakpoint/src/useMediaQuery-test.tsx
  packages/bpk-component-breakpoint/src/useMediaQuery.ts
  packages/bpk-component-datepicker/src/BpkDatepicker-test.tsx
  packages/bpk-component-datepicker/src/accessibility-test.tsx
Labels: patch

#3319 Fix linting
  packages/bpk-component-breakpoint/src/useMediaQuery-test.tsx
Labels: patch

#3321 [NOJIRA] [BpkPageIndicator] Add cursor hover behaviour
  packages/bpk-component-page-indicator/src/BpkPageIndicator.module.scss
Labels: minor

#3297 LOOM-1261 BpkAccordionItem - Moved className props out into existing and new spans
  packages/bpk-component-accordion/src/BpkAccordionItem.js
  packages/bpk-component-accordion/src/BpkAccordionItem.module.scss
  packages/bpk-component-accordion/src/__snapshots__/BpkAccordionItem-test.js.snap
  packages/bpk-component-accordion/src/__snapshots__/withAccordionItemState-test.js.snap
Labels: patch

#3324 LOOM-1277 BpkDataTableHeader
  packages/bpk-component-datatable/src/BpkDataTable-test.tsx
  packages/bpk-component-datatable/src/BpkDataTableHeader.module.scss
  packages/bpk-component-datatable/src/BpkDataTableHeader.tsx
  packages/bpk-component-datatable/src/__snapshots__/BpkDataTable-test.tsx.snap
  packages/bpk-component-datatable/src/__snapshots__/BpkDataTableHeader-test.tsx.snap
Labels: minor

#3320 LOOM-1274 BpkBreadcrumb Class 2 Overrides
  packages/bpk-component-breadcrumb/src/BpkBreadcrumbItem.js
  packages/bpk-component-breadcrumb/src/BpkBreadcrumbItem.module.scss
  packages/bpk-component-breadcrumb/src/__snapshots__/BpkBreadcrumbItem-test.js.snap
Labels: minor
