Repository Skyscanner/backpack, pull requests merged in 2024-04, with the labels that each got.

#3326 LOOM-1283 BpfFieldset Class 2 Overrides
  packages/bpk-component-fieldset/src/BpkFieldset.js
  packages/bpk-component-fieldset/src/__snapshots__/BpkFieldset-test.js.snap
Labels: minor

#3325 LOOM-1281 BpkDialog className moved to new wrapper span
  packages/bpk-component-dialog/src/BpkDialog.module.scss
  packages/bpk-component-dialog/src/BpkDialog.tsx
  packages/bpk-component-dialog/src/__snapshots__/BpkDialog-test.tsx.snap
Labels: patch

#3327 LOOM-1282 BkpDrawerContent BpkDrawer Class 2 Overrides
  packages/bpk-component-drawer/src/BpkDrawer.js
  packages/bpk-component-drawer/src/BpkDrawerContent.js
  packages/bpk-component-drawer/src/__snapshots__/BpkDrawer-test.js.snap
  packages/bpk-component-drawer/src/__snapshots__/BpkDrawerContent-test.js.snap
Labels: minor

#3331 LOOM-1287 BpkFormValidation moved className
  packages/bpk-component-fieldset/src/__snapshots__/BpkFieldset-test.js.snap
  packages/bpk-component-form-validation/src/BpkFormValidation.js
  packages/bpk-component-form-validation/src/__snapshots__/BpkFormValidation-test.js.snap
Labels: patch

#3333 LOOM-1289 BpkGridToggle removed className from BpkButtonLink out to wra…
  packages/bpk-component-grid-toggle/src/BpkGridToggle.js
  packages/bpk-component-grid-toggle/src/__snapshots__/BpkGridToggle-test.js.snap
Labels: patch

#3340 [MAT-1241] add test files
  packages/bpk-component-skeleton/src/BpkBaseSkeleton-test.tsx
  packages/bpk-component-skeleton/src/BpkBodyTextSkeleton-test.tsx
  packages/bpk-component-skeleton/src/BpkCircleSkeleton-test.tsx
  packages/bpk-component-skeleton/src/BpkHeadlineSkeleton-test.tsx
  packages/bpk-component-skeleton/src/BpkImageSkeleton-test.tsx
  packages/bpk-component-skeleton/src/accessibility-test.tsx
  packages/bpk-component-skeleton/src/utils-test.ts
Labels: minor

#3342 [MAT-1207] update readme file
  README.md
  packages/bpk-component-skeleton/README.md
Labels: minor

#3344 LOOM-1298 BpkPriceMarker Class 2 Overrides
  packages/bpk-component-map/src/BpkPriceMarker.js
  packages/bpk-component-map/src/__snapshots__/BpkPriceMarker-test.js.snap
Labels: minor

#3339 LOOM-1292 BpkInfoBannerInner - Class 2 Overrides
  packages/bpk-component-info-banner/src/BpkInfoBanner.module.scss
  packages/bpk-component-info-banner/src/BpkInfoBannerInner.tsx
  packages/bpk-component-info-banner/src/__snapshots__/BpkInfoBanner-test.tsx.snap
  packages/bpk-component-info-banner/src/__snapshots__/BpkInfoBannerDismissable-test.tsx.snap
  packages/bpk-component-info-banner/src/__snapshots__/BpkInfoBannerInner-test.tsx.snap
  packages/bpk-component-info-banner/src/__snapshots__/withBannerAlertState-test.tsx.snap
Labels: minor

#3352 [MAT-1205] optimize code for skeleton
  examples/bpk-component-skeleton/examples.tsx
  examples/bpk-component-skeleton/stories.ts
  packages/bpk-component-skeleton/README.md
  packages/bpk-component-skeleton/index.ts
  packages/bpk-component-skeleton/src/BpkBaseSkeleton-test.tsx
  packages/bpk-component-skeleton/src/BpkBaseSkeleton.d.tsx
  packages/bpk-component-skeleton/src/BpkBaseSkeleton.tsx
  packages/bpk-component-skeleton/src/BpkBodyTextSkeleton-test.tsx
  packages/bpk-component-skeleton/src/BpkBodyTextSkeleton.d.tsx
  packages/bpk-component-skeleton/src/BpkBodyTextSkeleton.module.scss
  packages/bpk-component-skeleton/src/BpkBodyTextSkeleton.tsx
  packages/bpk-component-skeleton/src/BpkCircleSkeleton-test.tsx
  packages/bpk-component-skeleton/src/BpkCircleSkeleton.d.tsx
  packages/bpk-component-skeleton/src/BpkCircleSkeleton.module.scss
  packages/bpk-component-skeleton/src/BpkCircleSkeleton.tsx
  packages/bpk-component-skeleton/src/BpkHeadlineSkeleton-test.tsx
  packages/bpk-component-skeleton/src/BpkHeadlineSkeleton.d.tsx
  packages/bpk-component-skeleton/src/BpkHeadlineSkeleton.module.scss
  packages/bpk-component-skeleton/src/BpkHeadlineSkeleton.tsx
  packages/bpk-component-skeleton/src/BpkImageSkeleton-test.tsx
  packages/bpk-component-skeleton/src/BpkImageSkeleton.d.tsx
  packages/bpk-component-skeleton/src/BpkImageSkeleton.module.scss
  packages/bpk-component-skeleton/src/BpkImageSkeleton.tsx
  packages/bpk-component-skeleton/src/BpkSkeleton-test.tsx
  packages/bpk-component-skeleton/src/BpkSkeleton.d.tsx
  packages/bpk-component-skeleton/src/BpkSkeleton.module.scss
  packages/bpk-component-skeleton/src/BpkSkeleton.tsx
  packages/bpk-component-skeleton/src/accessibility-test.tsx
  packages/bpk-component-skeleton/src/common-types.d.tsx
  packages/bpk-component-skeleton/src/common-types.tsx
  packages/bpk-component-skeleton/src/utils-test.ts
  packages/bpk-component-skeleton/src/utils.d.ts
  packages/bpk-component-skeleton/src/utils.ts
Labels: minor

#3355 NOJIRA: Add rating example with stars
  examples/bpk-component-rating/examples.js
  packages/bpk-component-rating/README.md
Labels: patch

#3354 LOOM-1314 BpkSectionListItem Class 2 Overrides
  packages/bpk-component-section-list/src/BpkSectionListItem.js
  packages/bpk-component-section-list/src/BpkSectionListItem.module.scss
  packages/bpk-component-section-list/src/__snapshots__/BpkSectionListItem-test.js.snap
Labels: minor

#3349 LOOM-1304 BpkNudger Class 2 Overrides
  packages/bpk-component-nudger/src/BpkNudger-test.tsx
  packages/bpk-component-nudger/src/BpkNudger.module.scss
  packages/bpk-component-nudger/src/BpkNudger.tsx
  packages/bpk-component-nudger/src/__snapshots__/BpkNudger-test.tsx.snap
Labels: minor

#3360 LOOM-1315 BpkSpinner moved className prop to wrapper span
  packages/bpk-component-image/src/__snapshots__/BpkBackgroundImage-test.tsx.snap
  packages/bpk-component-image/src/__snapshots__/BpkImage-test.tsx.snap
  packages/bpk-component-loading-button/src/__snapshots__/BpkLoadingButton-test.js.snap
  packages/bpk-component-spinner/src/BpkExtraLargeSpinner.js
  packages/bpk-component-spinner/src/BpkLargeSpinner.js
  packages/bpk-component-spinner/src/BpkSpinner.js
  packages/bpk-component-spinner/src/__snapshots__/BpkExtraLargeSpinner-test.js.snap
  packages/bpk-component-spinner/src/__snapshots__/BpkLargeSpinner-test.js.snap
  packages/bpk-component-spinner/src/__snapshots__/BpkSpinner-test.js.snap
Labels: patch

#3361 [LOOM-1302] - Update BpkNavigationBarButtonLink and Icon
  packages/bpk-component-modal/src/__snapshots__/BpkModalInner-test.tsx.snap
  packages/bpk-component-navigation-bar/src/BpkNavigationBarButtonLink.module.scss
  packages/bpk-component-navigation-bar/src/BpkNavigationBarButtonLink.tsx
  packages/bpk-component-navigation-bar/src/BpkNavigationBarIconButton.tsx
  packages/bpk-component-navigation-bar/src/__snapshots__/BpkNavigationBar-test.tsx.snap
  packages/bpk-component-navigation-bar/src/__snapshots__/BpkNavigationBarButtonLink-test.tsx.snap
  packages/bpk-component-navigation-bar/src/__snapshots__/BpkNavigationBarIconButton-test.tsx.snap
Labels: patch

#3362 LOOM-1316 BpkInteractiveStar Moved className on BpkStarNonRtl to wrapper div
  packages/bpk-component-star-rating/src/BpkInteractiveStar.js
  packages/bpk-component-star-rating/src/__snapshots__/BpkInteractiveStar-test.js.snap
  packages/bpk-component-star-rating/src/__snapshots__/BpkInteractiveStarRating-test.js.snap
  packages/bpk-component-star-rating/src/__snapshots__/withInteractiveStarRatingState-test.js.snap
Labels: patch

#3366 [BDES-144]: update svgs to include modified ai logo & new dot logo
  package-lock.json
  package.json
Labels: minor

#3364 [LOOM-1318] [BpkThemeToggle] classname prop update
  packages/bpk-component-theme-toggle/src/BpkThemeToggle.js
  packages/bpk-component-theme-toggle/src/__snapshots__/BpkThemeToggle-test.js.snap
Labels: patch

#3367 LOOM-1317 BpkStar Added spans around icons
  packages/bpk-component-star-rating/src/BpkStar.js
  packages/bpk-component-star-rating/src/BpkStar.module.scss
  packages/bpk-component-star-rating/src/__snapshots__/BpkInteractiveStar-test.js.snap
  packages/bpk-component-star-rating/src/__snapshots__/BpkInteractiveStarRating-test.js.snap
  packages/bpk-component-star-rating/src/__snapshots__/BpkStar-test.js.snap
  packages/bpk-component-star-rating/src/__snapshots__/BpkStarRating-test.js.snap
  packages/bpk-component-star-rating/src/__snapshots__/withInteractiveStarRatingState-test.js.snap
Labels: patch

#3372 [LOOM-1318][BpkCloseButton] Update Style and add onDark prop
  .stylelintrc.json
  packages/bpk-component-banner-alert/src/__snapshots__/BpkBannerAlertDismissable-test.tsx.snap
  packages/bpk-component-banner-alert/src/__snapshots__/BpkBannerAlertInner-test.tsx.snap
  packages/bpk-component-banner-alert/src/__snapshots__/withBannerAlertState-test.tsx.snap
  packages/bpk-component-bottom-sheet/src/__snapshots__/BpkBottomSheet-test.tsx.snap
  packages/bpk-component-close-button/src/BpkCloseButton.js
  packages/bpk-component-close-button/src/BpkCloseButton.module.scss
  packages/bpk-component-close-button/src/__snapshots__/BpkCloseButton-test.js.snap
  packages/bpk-component-dialog/src/__snapshots__/BpkDialog-test.tsx.snap
  packages/bpk-component-drawer/src/__snapshots__/BpkDrawer-test.js.snap
  packages/bpk-component-drawer/src/__snapshots__/BpkDrawerContent-test.js.snap
  packages/bpk-component-info-banner/src/__snapshots__/BpkInfoBannerDismissable-test.tsx.snap
  packages/bpk-component-info-banner/src/__snapshots__/BpkInfoBannerInner-test.tsx.snap
  packages/bpk-component-info-banner/src/__snapshots__/withBannerAlertState-test.tsx.snap
  packages/bpk-component-modal/src/BpkModalV2/__snapshots__/BpKModal-test.tsx.snap
  packages/bpk-component-modal/src/__snapshots__/BpkModal-test.tsx.snap
  packages/bpk-component-modal/src/__snapshots__/BpkModalInner-test.tsx.snap
  packages/bpk-component-navigation-bar/src/BpkNavigationBarIconButton.tsx
  packages/bpk-component-navigation-bar/src/__snapshots__/BpkNavigationBar-test.tsx.snap
  packages/bpk-component-navigation-bar/src/__snapshots__/BpkNavigationBarIconButton-test.tsx.snap
  packages/bpk-component-popover/src/__snapshots__/BpkPopover-test.js.snap
Labels: minor

#3275 [BDES-137][bpk-component-mobile-scroll-container] Removed edge fade
  packages/bpk-component-mobile-scroll-container/src/BpkMobileScrollContainer-test.js
  packages/bpk-component-mobile-scroll-container/src/BpkMobileScrollContainer.js
  packages/bpk-component-mobile-scroll-container/src/BpkMobileScrollContainer.module.scss
Labels: minor

#3376 [LOOM-1376][BpkMobileScrollContainer] Comment to declare the className as an accepted
  .eslintrc
  packages/bpk-component-mobile-scroll-container/src/BpkMobileScrollContainer.js
Labels: patch

#3375 [LOOM-1373][BpkSlider] Comment to declare the className as an accepted prop
  .eslintrc
  packages/bpk-component-slider/src/BpkSlider.tsx
Labels: patch

#3373 [LOOM-1368][BpkModal] Comment to declare the className as an accepted prop
  .eslintrc
  packages/bpk-component-modal/src/BpkModal.tsx
Labels: patch

#3377 LOOM-1367 BpkList Class 2 Overrides
  .eslintrc
  packages/bpk-component-list/src/BpkList.js
Labels: minor

#3381 [NOJIRA][BpkBreakpoint]: fix ssr re-render behaviour
  packages/bpk-component-breakpoint/src/BpkBreakpoint-test.tsx
  packages/bpk-component-breakpoint/src/BpkBreakpoint.tsx
Labels: patch

#3385 [ZOOT-992][BpkFloatingNotification] Increases floating notification's z-index to 2
  packages/bpk-component-floating-notification/src/BpkFloatingNotification.module.scss
Labels: patch

#3384 [BD-7842][BpkMap] Add scaleControl prop for BpkMap component
  packages/bpk-component-map/src/BpkMap.js
Labels: minor

#3382 [LOOM-1278][BpkBarChart] Class 2 Fix Remove unused classname prop
  packages/bpk-component-barchart/src/BpkBarchart-test.js
  packages/bpk-component-barchart/src/BpkBarchart.js
  packages/bpk-component-barchart/src/__snapshots__/BpkBarchart-test.js.snap
Labels: major

#3383 [LOOM-1287][BpkDismissibleChip][BpkSelectableChip] - Class 2 fixes
  .eslintrc
  packages/bpk-component-chip/src/BpkDismissibleChip.tsx
  packages/bpk-component-chip/src/BpkSelectableChip.tsx
  packages/bpk-component-chip/src/__snapshots__/BpkDismissibleChip-test.tsx.snap
Labels: patch

#3386 LOOM-1307 BpkPhoneInput Class 2 Overrides
  packages/bpk-component-phone-input/src/BpkPhoneInput.js
  packages/bpk-component-phone-input/src/__snapshots__/BpkPhoneInput-test.js.snap
Labels: minor

#3370 Split definitions for group types
  packages/bpk-component-chip-group/src/BpkChipGroup.tsx
  packages/bpk-component-chip-group/src/BpkChipGroupSingleSelect.tsx
Labels: skip-changelog

#3388 [LOOM-1280][BpkDatePicker] Remove useless styling
  packages/bpk-component-datepicker/src/BpkDatepicker.module.scss
  packages/bpk-component-datepicker/src/BpkDatepicker.tsx
  packages/bpk-component-datepicker/src/__snapshots__/BpkDatepicker-test.tsx.snap
Labels: patch

#3394 LOOM-1315 BpkSpinner animation fix
  packages/bpk-component-spinner/src/BpkSpinner.module.scss
Labels: patch

#3398 Revert "[LOOM-1278][BpkBarChart] Class 2 Fix Remove unused classname prop"
  packages/bpk-component-barchart/src/BpkBarchart-test.js
  packages/bpk-component-barchart/src/BpkBarchart.js
  packages/bpk-component-barchart/src/__snapshots__/BpkBarchart-test.js.snap
Labels: skip-changelog

#3389 [LOOM-1284][BpkFlare] Fix class 2 CSS issues for BpkFlare
  .eslintrc
  examples/bpk-component-flare/examples.js
  examples/bpk-component-flare/examples.module.scss
  examples/bpk-component-flare/stories.js
  packages/bpk-component-dialog/src/__snapshots__/BpkDialog-test.tsx.snap
  packages/bpk-component-flare/src/BpkContentBubble.js
  packages/bpk-component-flare/src/BpkFlareBar.js
  packages/bpk-component-flare/src/__snapshots__/BpkContentBubble-test.js.snap
  packages/bpk-component-flare/src/bpk-content-bubble.module.scss
  packages/bpk-component-flare/src/bpk-flare-bar.module.scss
Labels: patch

#3397 [LOOM-1286][BpkFloatingNotification]: remove className usage from BpkFloatingNotification
  examples/bpk-component-aria-live/examples.tsx
  examples/bpk-component-bottom-sheet/examples.tsx
  examples/bpk-component-card-button/stories.tsx
  examples/bpk-component-chip/examples.tsx
  examples/bpk-component-chip/stories.tsx
  examples/bpk-component-content-cards/examples.tsx
  examples/bpk-component-content-cards/stories.ts
  examples/bpk-component-datatable/examples.tsx
  examples/bpk-component-datatable/stories.tsx
  examples/bpk-component-floating-notification/examples.tsx
  examples/bpk-component-floating-notification/stories.tsx
  examples/bpk-component-modal-v2/examples.tsx
  examples/bpk-component-overlay/stories.tsx
  examples/bpk-component-section-header/stories.ts
  packages/bpk-component-datatable/src/common-types.ts
  packages/bpk-component-floating-notification/src/BpkFloatingNotification-test.tsx
  packages/bpk-component-floating-notification/src/BpkFloatingNotification.module.scss
  packages/bpk-component-floating-notification/src/BpkFloatingNotification.tsx
  packages/bpk-component-floating-notification/src/__snapshots__/BpkFloatingNotification-test.tsx.snap
  packages/bpk-component-floating-notification/src/accessibility-test.tsx
  tsconfig.json
Labels: patch
