Repository Skyscanner/backpack, pull requests merged in 2024-10, with the labels that each got.

#3623 [NO JIRA][FloatingNotification]: Update floating notification dismiss timeout
  examples/bpk-component-floating-notification/examples.tsx
Labels: skip-changelog

#3634 [NO JIRA][BpkNavigationTabGroup]Modify Navigation Tab Group A11Y
  packages/bpk-component-navigation-tab-group/README.md
  packages/bpk-component-navigation-tab-group/src/BpkNavigationTabGroup.module.scss
  packages/bpk-component-navigation-tab-group/src/BpkNavigationTabGroup.tsx
Labels: minor

#3643 CAPY-889 Add xsmall to BpkPrice component
  examples/bpk-component-price/examples.js
  examples/bpk-component-price/stories.js
  packages/bpk-component-price/src/BpkPrice-test.js
  packages/bpk-component-price/src/BpkPrice.js
  packages/bpk-component-price/src/__snapshots__/BpkPrice-test.js.snap
  packages/bpk-component-price/src/common-types.js
Labels: minor

#3644 [LUNA-2015][BpkSwitch] Adds focus indicator
  packages/bpk-component-switch/src/BpkSwitch.module.scss
Labels: patch

#3632 [BDES-96] [BpkCardList] Base Component
  examples/bpk-component-card-list/examples.tsx
  examples/bpk-component-card-list/stories.ts
  packages/bpk-component-card-list/README.md
  packages/bpk-component-card-list/index.ts
  packages/bpk-component-card-list/src/BpkCardList-test.tsx
  packages/bpk-component-card-list/src/BpkCardList.module.scss
  packages/bpk-component-card-list/src/BpkCardList.tsx
  packages/bpk-component-card-list/src/accessibility-test.tsx
  packages/bpk-component-card-list/src/common-types.ts
Labels: patch

#3650 [NoJira] Remove styles-dev script which is not used
  scripts/scss/styles-dev.js
Labels: skip-changelog

#3649 [NoJira][BpkTicket] Deprecate BpkTicket component
  packages/bpk-component-ticket/README.md
  packages/bpk-component-ticket/src/BpkTicket.js
Labels: patch

#3651 [NoJira] Remove chokidar library
  package-lock.json
  package.json
Labels: skip-changelog

#3652 [WEAV-2560][BpkSegmentedControl] Focus Border fix
  packages/bpk-component-segmented-control/src/BpkSegmentedControl.module.scss
Labels: javascript, patch

#3645 [NoJira][BpkSlider] - Fix native event handling for the Slider
  packages/bpk-component-checkbox/src/form-test.js
  packages/bpk-component-datepicker/src/form-test.tsx
  packages/bpk-component-input/src/form-test.tsx
  packages/bpk-component-nudger/src/form-test.tsx
  packages/bpk-component-phone-input/src/form-test.js
  packages/bpk-component-radio/src/form-test.js
  packages/bpk-component-select/src/form-test.js
  packages/bpk-component-slider/README.md
  packages/bpk-component-slider/src/BpkSlider.tsx
  packages/bpk-component-slider/src/form-test.tsx
  packages/bpk-component-split-input/src/form-test.tsx
  packages/bpk-component-switch/src/form-test.tsx
  packages/package-lock.json
  packages/package.json
Labels: javascript, patch

#3646 [IRN-5328] [BpkDrawer] supports non-padded content
  examples/bpk-component-drawer/examples.js
  examples/bpk-component-drawer/examples.module.scss
  examples/bpk-component-drawer/stories.js
  packages/bpk-component-drawer/src/BpkDrawer.js
  packages/bpk-component-drawer/src/BpkDrawerContent-test.tsx
  packages/bpk-component-drawer/src/BpkDrawerContent.module.scss
  packages/bpk-component-drawer/src/BpkDrawerContent.tsx
  packages/bpk-component-drawer/src/__snapshots__/BpkDrawer-test.js.snap
  packages/bpk-component-drawer/src/__snapshots__/BpkDrawerContent-test.tsx.snap
Labels: minor

#3658 CAPY[909] Remove min width & height on BpkDividedCard
  examples/bpk-component-card/examples.js
  packages/bpk-component-card/src/BpkDividedCard.module.scss
Labels: major

#3659 Revert "CAPY[909] Remove min width & height on BpkDividedCard"
  examples/bpk-component-card/examples.js
  packages/bpk-component-card/src/BpkDividedCard.module.scss
Labels: minor

#3660 [CAPY-909][BpkDividedCard] Remove min width & height on BpkDividedCard - Redo
  examples/bpk-component-card/examples.js
  packages/bpk-component-card/src/BpkDividedCard.module.scss
Labels: major
