Repository Skyscanner/backpack, pull requests merged in 2024-06, with the labels that each got.

#3481 [WALL-1807][BpkText] Update hero text styles
  examples/bpk-component-text/examples.js
  package-lock.json
  package.json
  packages/bpk-component-text/src/BpkText.module.scss
  packages/bpk-component-text/src/BpkText.tsx
  packages/bpk-mixins/_typography.scss
  packages/package-lock.json
  packages/package.json
Labels: dependencies, javascript, minor

#3486 [NOJIRA][BpkPopover] Fix Popover cannot be closed by changing `isOpen`
  packages/bpk-component-popover/src/BpkPopover-test.tsx
  packages/bpk-component-popover/src/BpkPopover.tsx
Labels: minor

#3487 [IRN-5089][bpk-mixins] Improve ScreenReader focus indictor for visually hidden
  packages/bpk-mixins/_utils.scss
  packages/bpk-stylesheets/base.css
Labels: minor

#3467 [ARGG-1143]: Add changed files check for running Percy
  .github/workflows/_build.yml
Labels: skip-changelog

#3059 [BD-8468][BpkCarousel] new component for mobile
  examples/bpk-component-carousel/example.js
  examples/bpk-component-carousel/stories.js
  packages/bpk-component-carousel/README.md
  packages/bpk-component-carousel/index.ts
  packages/bpk-component-carousel/src/BpkCarousel-test.tsx
  packages/bpk-component-carousel/src/BpkCarousel.module.scss
  packages/bpk-component-carousel/src/BpkCarousel.tsx
  packages/bpk-component-carousel/src/BpkCarouselContainer.module.scss
  packages/bpk-component-carousel/src/BpkCarouselContainer.tsx
  packages/bpk-component-carousel/src/BpkCarouselImage.module.scss
  packages/bpk-component-carousel/src/BpkCarouselImage.tsx
  packages/bpk-component-carousel/src/accessibility-test.tsx
  packages/bpk-component-carousel/src/types.ts
  packages/bpk-component-carousel/src/utils.tsx
  packages/bpk-component-page-indicator/src/BpkPageIndicator-test.js
  packages/bpk-component-page-indicator/src/BpkPageIndicator.js
  packages/bpk-component-page-indicator/src/__snapshots__/BpkPageIndicator-test.js.snap
Labels: minor

#3489 [NO JIRA][BpkPopover]: Turn off autoplacement for now and add visual tests
  examples/bpk-component-popover/examples.js
  examples/bpk-component-popover/stories.js
  packages/bpk-component-popover/src/BpkPopover-test.tsx
  packages/bpk-component-popover/src/BpkPopover.tsx
  packages/bpk-component-popover/src/accessibility-test.tsx
Labels: patch

#3496 Updates the BpkDrawer component README to useState
  packages/bpk-component-drawer/README.md
Labels: patch

#3491 NO-JIRA: BpkSlider docs- add note on min distance
  examples/bpk-component-slider/stories.js
Labels: skip-changelog

#3495 [NOJIRA][BpkPopover] Fix Popover issue that floating-ui's useClick does not support stopPropagation
  packages/bpk-component-popover/src/BpkPopover-test.tsx
  packages/bpk-component-popover/src/BpkPopover.tsx
Labels: patch

#3501 [LUNA-1589][BpkSaveButton] Updates Save Button cursor
  packages/bpk-component-card-button/src/BpkSaveButton.module.scss
Labels: patch

#3503 [ARGG-1141] Add accessibility DoD
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: skip-changelog

#3504 [BDES-163][BpkPrice]: Update BpkPrice previousPrice colour
  packages/bpk-component-price/src/BpkPrice.module.scss
Labels: minor

#3482 [LUNA-1231][BpkSegmentedControl] Add segmented control component
  examples/bpk-component-segmented-control/examples.tsx
  examples/bpk-component-segmented-control/stories.tsx
  packages/bpk-component-segmented-control/README.md
  packages/bpk-component-segmented-control/index.ts
  packages/bpk-component-segmented-control/src/BpkSegmentedControl-test.tsx
  packages/bpk-component-segmented-control/src/BpkSegmentedControl.module.scss
  packages/bpk-component-segmented-control/src/BpkSegmentedControl.tsx
  packages/bpk-component-segmented-control/src/accessibility-test.tsx
Labels: minor

#3507 [NO JIRA]: Update Segmented control examples as per design request and docs
  examples/bpk-component-segmented-control/examples.tsx
  examples/bpk-component-segmented-control/stories.tsx
Labels: skip-changelog

#3497 [NO JIRA][BpkPopover]: Update popover to attach to body outside of target elements
  packages/bpk-component-popover/src/BpkPopover-test.tsx
  packages/bpk-component-popover/src/BpkPopover.tsx
Labels: patch

#3514 [ACC-568][BpkSaveButton] Accessibility improvements
  examples/bpk-component-card-button/examples.tsx
  packages/bpk-component-card-button/README.md
  packages/bpk-component-card-button/src/BpkSaveButton.tsx
  packages/bpk-component-card-button/src/__snapshots__/BpkSaveButton-test.tsx.snap
Labels: minor, Accessibility

#3515 [NO JIRA]: remove stop propgation that blocks keyboard events
  packages/bpk-component-input/src/withOpenEvents.tsx
Labels: patch
