Repository Skyscanner/backpack, pull requests merged in 2024-09, with the labels that each got.

#3599 [PANGOO-2516][BpkNavigationTabGroup] Add Navigation-tab-group component
  README.md
  examples/bpk-component-navigation-tab-group/examples.module.scss
  examples/bpk-component-navigation-tab-group/examples.tsx
  examples/bpk-component-navigation-tab-group/stories.tsx
  packages/bpk-component-navigation-tab-group/README.md
  packages/bpk-component-navigation-tab-group/index.ts
  packages/bpk-component-navigation-tab-group/src/BpkNavigationTabGroup-test.tsx
  packages/bpk-component-navigation-tab-group/src/BpkNavigationTabGroup.module.scss
  packages/bpk-component-navigation-tab-group/src/BpkNavigationTabGroup.tsx
  packages/bpk-component-navigation-tab-group/src/accessibility-test.tsx
Labels: minor

#3610 Revert "Bump css-loader from 6.10.0 to 7.1.2"
  package-lock.json
  package.json
Labels: skip-changelog

#3607 [PANGOO-2581][BpkNavigationTabGroup]Add Extra Props in BPK NavTabGroup
  examples/bpk-component-navigation-tab-group/examples.tsx
  packages/bpk-component-navigation-tab-group/README.md
  packages/bpk-component-navigation-tab-group/src/BpkNavigationTabGroup-test.tsx
  packages/bpk-component-navigation-tab-group/src/BpkNavigationTabGroup.tsx
  packages/bpk-component-navigation-tab-group/src/accessibility-test.tsx
Labels: minor

#3616 [BpkRadio] update Storybook example
  examples/bpk-component-radio/examples.js
Labels: skip-changelog, Accessibility

#3617 [BD-8797][BpkSaveButton]Update it to support extension props
  packages/bpk-component-card-button/src/BpkSaveButton.tsx
Labels: minor

#3618 [PANGOO-2594][BpkNavigationTabGroup]Fix BPK NavTabGroup Warning
  examples/bpk-component-navigation-tab-group/examples.tsx
  packages/bpk-component-navigation-tab-group/src/BpkNavigationTabGroup.tsx
Labels: minor
