Repository Skyscanner/backpack, pull requests merged in 2024-11, with the labels that each got.

#3667 [COR-481][BpkDrawer] Update backpack drawer to tsx
  package-lock.json
  package.json
  packages/bpk-component-banner-alert/src/AnimateAndFade.tsx
  packages/bpk-component-drawer/index.ts
  packages/bpk-component-drawer/src/BpkDrawer-test.tsx
  packages/bpk-component-drawer/src/BpkDrawer.js
  packages/bpk-component-drawer/src/BpkDrawer.tsx
  packages/bpk-component-drawer/src/BpkDrawerContent-test.tsx
  packages/bpk-component-drawer/src/BpkDrawerContent.tsx
  packages/bpk-component-drawer/src/__snapshots__/BpkDrawer-test.tsx.snap
  packages/bpk-component-drawer/src/accessibility-test.tsx
  packages/bpk-component-drawer/src/themeAttributes-test.ts
  packages/bpk-component-drawer/src/themeAttributes.ts
  packages/bpk-component-floating-notification/src/BpkFloatingNotification.tsx
  packages/bpk-component-image/src/BpkBackgroundImage.tsx
  packages/bpk-component-image/src/BpkImage.tsx
  packages/bpk-component-info-banner/src/AnimateAndFade.tsx
  packages/bpk-react-utils/src/BpkDialogWrapper/BpkDialogWrapper.tsx
  packages/bpk-react-utils/src/TransitionInitialMount.tsx
Labels: minor

#3668 [BD-9128][BpkIconMarkerBackground] Add aria-hidden to fix a11y issue
  packages/bpk-component-map/src/BpkIconMarkerBackground.js
  packages/bpk-component-map/src/__snapshots__/BpkIconMarker-test.js.snap
  packages/bpk-component-map/src/__snapshots__/BpkIconMarkerBackground-test.js.snap
Labels: patch

#3670 [COR-481][BpkDrawer] Removing header border
  packages/bpk-component-drawer/src/BpkDrawer.tsx
  packages/bpk-component-drawer/src/BpkDrawerContent.module.scss
  packages/bpk-component-drawer/src/BpkDrawerContent.tsx
Labels: patch

#3675 [LOOM-1942][BpkPrice]: Fix right aligned price layout
  packages/bpk-component-price/src/BpkPrice.module.scss
Labels: patch

#3676 [Storybook] BpkButton, fix accessibility violation
  examples/bpk-component-button/examples.tsx
Labels: skip-changelog

#3674 [NO-JIRA][BpkAccordion]: Fix flow types in BpkAccordion
  examples/bpk-component-accordion/examples.tsx
  examples/bpk-component-accordion/stories-utils.tsx
  examples/bpk-component-accordion/stories.tsx
  packages/bpk-component-accordion/index.ts
  packages/bpk-component-accordion/src/BpkAccordion-test.tsx
  packages/bpk-component-accordion/src/BpkAccordion.tsx
  packages/bpk-component-accordion/src/BpkAccordionItem-test.tsx
  packages/bpk-component-accordion/src/BpkAccordionItem.tsx
  packages/bpk-component-accordion/src/__snapshots__/BpkAccordion-test.tsx.snap
  packages/bpk-component-accordion/src/__snapshots__/BpkAccordionItem-test.tsx.snap
  packages/bpk-component-accordion/src/__snapshots__/withAccordionItemState-test.tsx.snap
  packages/bpk-component-accordion/src/__snapshots__/withSingleItemAccordionState-test.tsx.snap
  packages/bpk-component-accordion/src/accessibility-test.tsx
  packages/bpk-component-accordion/src/withAccordionItemState-test.tsx
  packages/bpk-component-accordion/src/withAccordionItemState.tsx
  packages/bpk-component-accordion/src/withSingleItemAccordionState-test.tsx
  packages/bpk-component-accordion/src/withSingleItemAccordionState.tsx
Labels: patch

#3682 [COR-481][BpkDrawer] Drawer Ipad Setting Fix
  packages/bpk-component-drawer/src/BpkDrawer.tsx
Labels: patch

#3683 [NO JIRA][maintenance]: Bump bpk-svgs to latest for up to date icons
  package-lock.json
  package.json
  packages/package-lock.json
  packages/package.json
Labels: minor

#3684 [NO-JIRA] [bpk-stylesheets] Added stylesheet compatible with modern Sass compiler
  packages/bpk-mixins/_tokens.scss
Labels: minor
