Repository Skyscanner/backpack, pull requests merged in 2024-08, with the labels that each got.

#3531 [CYB-2251][Snippet] Add new Snippet component
  examples/bpk-component-snippet/examples.tsx
  examples/bpk-component-snippet/stories.tsx
  packages/bpk-component-snippet/README.md
  packages/bpk-component-snippet/index.ts
  packages/bpk-component-snippet/src/BpkSnippet-test.tsx
  packages/bpk-component-snippet/src/BpkSnippet.module.scss
  packages/bpk-component-snippet/src/BpkSnippet.tsx
  packages/bpk-component-snippet/src/accessibility-test.tsx
Labels: minor

#3574 NO-JIRA: Added submit to loading button props
  examples/bpk-component-button/examples.tsx
  examples/bpk-component-button/stories.tsx
  examples/bpk-component-loading-button/examples.js
  examples/bpk-component-loading-button/stories.js
  packages/bpk-component-loading-button/src/BpkLoadingButton.tsx
Labels: patch

#3567 [LOOM-1520][BpkSlider] Fix for Slider to support Form properly
  examples/bpk-component-slider/examples.js
  packages/bpk-component-slider/src/BpkSlider.tsx
  packages/bpk-component-slider/src/__snapshots__/BpkSlider-test.tsx.snap
  packages/package-lock.json
  packages/package.json
Labels: enhancement, javascript, minor

#3565 LOOM-1540: tsx migration for splitinput and inputField components
  decisions/accessibility-tests.md
  examples/bpk-component-fieldset/examples.js
  examples/bpk-component-split-input/examples.js
  packages/bpk-component-input/src/BpkInput.tsx
  packages/bpk-component-input/src/common-types.ts
  packages/bpk-component-split-input/src/BpkInputField.tsx
  packages/bpk-component-split-input/src/BpkSplitInput-test.js
  packages/bpk-component-split-input/src/BpkSplitInput-test.tsx
  packages/bpk-component-split-input/src/BpkSplitInput.tsx
  packages/bpk-component-split-input/src/__snapshots__/BpkSplitInput-test.js.snap
  packages/bpk-component-split-input/src/accessibility-test.tsx
  packages/bpk-component-split-input/src/form-test.tsx
Labels: enhancement, major

#3579 [Loom-1535] - add form-test to bpkSlider
  packages/bpk-component-slider/src/form-test.tsx
Labels: enhancement, minor

#3576 [BpkNudger] Simplify nudger to make it support only number types
  examples/bpk-component-nudger/examples.js
  examples/bpk-component-nudger/stories.js
  packages/bpk-component-nudger/index.ts
  packages/bpk-component-nudger/src/BpkConfigurableNudger.tsx
  packages/bpk-component-nudger/src/BpkNudger-test.tsx
  packages/bpk-component-nudger/src/BpkNudger.module.scss
  packages/bpk-component-nudger/src/BpkNudger.tsx
  packages/bpk-component-nudger/src/__snapshots__/BpkNudger-test.tsx.snap
  packages/bpk-component-nudger/src/accessibility-test.tsx
  packages/bpk-component-nudger/src/common-types.ts
  packages/bpk-component-nudger/src/form-test.tsx
  packages/bpk-react-utils/src/nativeEventHandler.ts
Labels: enhancement, javascript, major

#3586 [NO JIRA][BpkSpinner]: Updating TS types and removing propTypes ahead of React 18
  packages/bpk-component-spinner/src/BpkExtraLargeSpinner-test.tsx
  packages/bpk-component-spinner/src/BpkExtraLargeSpinner.tsx
  packages/bpk-component-spinner/src/BpkLargeSpinner-test.tsx
  packages/bpk-component-spinner/src/BpkLargeSpinner.tsx
  packages/bpk-component-spinner/src/BpkSpinner-test.tsx
  packages/bpk-component-spinner/src/BpkSpinner.tsx
  packages/bpk-component-spinner/src/__snapshots__/BpkExtraLargeSpinner-test.tsx.snap
  packages/bpk-component-spinner/src/__snapshots__/BpkLargeSpinner-test.tsx.snap
  packages/bpk-component-spinner/src/__snapshots__/BpkSpinner-test.tsx.snap
  packages/bpk-component-spinner/src/accessibility-test.tsx
  packages/bpk-component-spinner/src/themeAttributes-test.tsx
Labels: patch

#3587 [NO JIRA][BpkCloseButton]: Updating to TS and removing propTypes ahead of React 18
  packages/bpk-component-close-button/src/BpkCloseButton-test.tsx
  packages/bpk-component-close-button/src/BpkCloseButton.tsx
  packages/bpk-component-close-button/src/__snapshots__/BpkCloseButton-test.tsx.snap
  packages/bpk-component-close-button/src/accessibility-test.tsx
Labels: patch

#3588 [NO JIRA][BpkLoadingButton]: Updating TS types and removing propTypes ahead of React 18
  packages/bpk-component-loading-button/src/BpkLoadingButton-test.tsx
  packages/bpk-component-loading-button/src/BpkLoadingButton.tsx
  packages/bpk-component-loading-button/src/__snapshots__/BpkLoadingButton-test.js.snap
  packages/bpk-component-loading-button/src/__snapshots__/BpkLoadingButton-test.tsx.snap
  packages/bpk-component-loading-button/src/accessibility-test.tsx
Labels: patch

#3591 [NO JIRA][BpkSplitInput]: Fix default state of inputValue
  packages/bpk-component-split-input/src/BpkSplitInput.tsx
Labels: patch

#3592 [NO-JIRA] [BpkInsetBanner] Update stories UI styles to match docs
  examples/bpk-component-inset-banner/examples.tsx
Labels: skip-changelog

#3582 [NO JIRA][BpkSwitch]: Remove label and just ship switch
  examples/bpk-component-aria-live/examples.module.scss
  examples/bpk-component-aria-live/examples.tsx
  examples/bpk-component-switch/examples.tsx
  examples/bpk-component-switch/stories.tsx
  packages/bpk-component-switch/index.ts
  packages/bpk-component-switch/src/BpkSwitch-test.js
  packages/bpk-component-switch/src/BpkSwitch-test.tsx
  packages/bpk-component-switch/src/BpkSwitch.module.scss
  packages/bpk-component-switch/src/BpkSwitch.tsx
  packages/bpk-component-switch/src/__snapshots__/BpkSwitch-test.js.snap
  packages/bpk-component-switch/src/accessibility-test.tsx
  packages/bpk-component-switch/src/form-test.tsx
  packages/bpk-component-switch/src/themeAttributes-test.tsx
  packages/bpk-component-switch/src/themeAttributes.ts
Labels: major

#3598 [NO JIRA]: Correct React semver range
  packages/package-lock.json
  packages/package.json
Labels: patch
