Repository Skyscanner/backpack, pull requests merged in 2024-01, with the labels that each got.

#3144 [NOJIRA]: add mini-css-extract-plugin
  .storybook/webpack.config.js
  examples/bpk-component-datepicker/examples.js
  examples/bpk-component-grid-toggle/stories.js
  package-lock.json
  packages/bpk-component-grid-toggle/index.js
Labels: skip-changelog

#3145 [NOJIRA]: add npmrc to point to public reg
  .npmrc
Labels: skip-changelog

#3146 [NOJIRA]: Percy add enable-javascript
  .percy.yml
Labels: skip-changelog

#3142 [DTO-5004][BpkInfoBanner] Remove Alert Role
  packages/bpk-component-info-banner/src/BpkInfoBanner-test.tsx
  packages/bpk-component-info-banner/src/BpkInfoBanner.tsx
  packages/bpk-component-info-banner/src/BpkInfoBannerInner.tsx
  packages/bpk-component-info-banner/src/__snapshots__/BpkInfoBanner-test.tsx.snap
  packages/bpk-component-info-banner/src/__snapshots__/BpkInfoBannerDismissable-test.tsx.snap
  packages/bpk-component-info-banner/src/__snapshots__/BpkInfoBannerInner-test.tsx.snap
  packages/bpk-component-info-banner/src/__snapshots__/withBannerAlertState-test.tsx.snap
Labels: patch

#3169 [ARGG-927][BpkBreakpoint] Update breakpoint to remove hydration mismatch error
  packages/bpk-component-breakpoint/src/BpkBreakpoint.tsx
  packages/bpk-component-breakpoint/src/__snapshots__/BpkBreakpoint-test.tsx.snap
Labels: patch

#3170 [NoJira] - set versioning-strategy to update package.json as well in dependabot
  .github/dependabot.yml
Labels: skip-changelog

#3182 [THES-154] BpkBottomSheet fix focus lock - accessibility
  packages/bpk-component-bottom-sheet/README.md
  packages/bpk-component-bottom-sheet/src/BpkBottomSheetInner-test.tsx
  packages/bpk-component-bottom-sheet/src/BpkBottomSheetInner.d.ts
  packages/bpk-component-bottom-sheet/src/BpkBottomSheetInner.module.css
  packages/bpk-component-bottom-sheet/src/BpkBottomSheetInner.module.scss
  packages/bpk-component-bottom-sheet/src/BpkBottomSheetInner.tsx
Labels: patch

#3157 Update boilerplate to remove className, update contribution and add danger check
  CONTRIBUTING.md
  dangerfile.ts
  packages/bpk-component-boilerplate/src/BpkBoilerplate-test.tsx
  packages/bpk-component-boilerplate/src/BpkBoilerplate.d.ts
  packages/bpk-component-boilerplate/src/BpkBoilerplate.tsx
  packages/bpk-component-boilerplate/src/__snapshots__/BpkBoilerplate-test.tsx.snap
Labels: skip-changelog

#3181 [LUNA-1092] [BpkSwapButton] Contribute to Backpack
  examples/bpk-component-swap-button/examples.js
  examples/bpk-component-swap-button/stories.js
  packages/bpk-component-swap-button/README.md
  packages/bpk-component-swap-button/index.d.ts
  packages/bpk-component-swap-button/index.ts
  packages/bpk-component-swap-button/src/BpkSwapButton-test.tsx
  packages/bpk-component-swap-button/src/BpkSwapButton.d.ts
  packages/bpk-component-swap-button/src/BpkSwapButton.module.css
  packages/bpk-component-swap-button/src/BpkSwapButton.module.scss
  packages/bpk-component-swap-button/src/BpkSwapButton.tsx
  packages/bpk-component-swap-button/src/__snapshots__/BpkSwapButton-test.tsx.snap
  packages/bpk-component-swap-button/src/accessibility-test.tsx
Labels: minor

#3197 [Luna 1092] - BpkSwapButton Fix Aria Props
  packages/bpk-component-swap-button/README.md
  packages/bpk-component-swap-button/src/BpkSwapButton-test.tsx
  packages/bpk-component-swap-button/src/BpkSwapButton.tsx
  packages/bpk-component-swap-button/src/__snapshots__/BpkSwapButton-test.tsx.snap
  packages/bpk-component-swap-button/src/accessibility-test.tsx
Labels: patch

#3196 Luna 1092 patch
  examples/bpk-component-swap-button/examples.js
  examples/bpk-component-swap-button/stories.js
  packages/bpk-component-swap-button/src/BpkSwapButton.module.css
  packages/bpk-component-swap-button/src/BpkSwapButton.module.scss
  packages/bpk-component-swap-button/src/BpkSwapButton.tsx
  packages/bpk-component-swap-button/src/__snapshots__/BpkSwapButton-test.tsx.snap
Labels: patch

#3199 [BpkSwapButton]: Updating exported typescript declarations for docs and usage
  examples/bpk-component-swap-button/examples.js
  packages/bpk-component-swap-button/index.d.ts
  packages/bpk-component-swap-button/index.ts
  packages/bpk-component-swap-button/src/BpkSwapButton.d.ts
Labels: patch

#3200 Removing important from focus indicator to avoid overrides with layers
  packages/bpk-mixins/src/mixins/_utils.scss
  packages/bpk-stylesheets/base.css
Labels: patch

#3204 ST-5444 Updating npm version to match LTS/Node stable pairing
  package-lock.json
  package.json
  packages/package-lock.json
  packages/package.json
Labels: patch

#3205 [THES-158] BpkBottomSheet fix empty heading - accessibility
  examples/bpk-component-bottom-sheet/examples.tsx
  examples/bpk-component-bottom-sheet/stories.js
  packages/bpk-component-bottom-sheet/src/BpkBottomSheetInner-test.tsx
  packages/bpk-component-bottom-sheet/src/BpkBottomSheetInner.tsx
  packages/bpk-component-bottom-sheet/src/__snapshots__/BpkBottomSheetInner-test.tsx.snap
Labels: patch

#3207 Fix the switch when it is in a container without enough space
  examples/bpk-component-switch/examples.js
  examples/bpk-component-switch/stories.js
  packages/bpk-component-switch/src/BpkSwitch.module.css
  packages/bpk-component-switch/src/BpkSwitch.module.scss
Labels: patch
