Repository Skyscanner/backpack, pull requests merged in 2024-05, with the labels that each got.

#3401 [LOOM-1393][BpkCalendar] Accepted class 2 rules
  .eslintrc
  packages/bpk-component-calendar/src/BpkCalendarGridTransition.tsx
  packages/bpk-component-calendar/src/BpkCalendarNav.tsx
  packages/bpk-component-calendar/src/BpkCalendarWeek.tsx
Labels: patch

#3403 [LOOM-1295][BpkClearButton] Remove the BpkClearButton integrate directly with the BpkInput
  packages/bpk-component-input/src/BpkClearButton-test.tsx
  packages/bpk-component-input/src/BpkClearButton.d.ts
  packages/bpk-component-input/src/BpkClearButton.module.scss
  packages/bpk-component-input/src/BpkClearButton.tsx
  packages/bpk-component-input/src/BpkInput.tsx
  packages/bpk-component-input/src/__snapshots__/BpkClearButton-test.tsx.snap
  packages/bpk-mixins/_forms.scss
Labels: patch

#3407 ChipGroup - Remove label padding
  examples/bpk-component-chip-group/examples.tsx
  packages/bpk-component-chip-group/src/BpkChipGroup.module.scss
  packages/bpk-component-chip-group/src/BpkChipGroup.tsx
  packages/bpk-component-chip-group/src/BpkChipGroupSingleSelect.tsx
Labels: skip-changelog

#3411 ChipGroup Update typedefs for nudger labels
  packages/bpk-component-chip-group/src/BpkChipGroup.d.ts
Labels: skip-changelog

#3393 [IRN-5018][BpkNavigationBar][BpkBottomSheet] Add handling for long title text
  examples/bpk-component-bottom-sheet/examples.tsx
  examples/bpk-component-bottom-sheet/stories.js
  examples/bpk-component-navigation-bar/examples.js
  examples/bpk-component-navigation-bar/stories.js
  packages/bpk-component-bottom-sheet/src/BpkBottomSheet.module.scss
  packages/bpk-component-bottom-sheet/src/BpkBottomSheet.tsx
  packages/bpk-component-bottom-sheet/src/__snapshots__/BpkBottomSheet-test.tsx.snap
  packages/bpk-component-modal/src/__snapshots__/BpkModal-test.tsx.snap
  packages/bpk-component-modal/src/__snapshots__/BpkModalInner-test.tsx.snap
  packages/bpk-component-navigation-bar/index.d.ts
  packages/bpk-component-navigation-bar/src/BpkNavigationBar.d.ts
  packages/bpk-component-navigation-bar/src/BpkNavigationBar.module.scss
  packages/bpk-component-navigation-bar/src/BpkNavigationBar.tsx
  packages/bpk-component-navigation-bar/src/BpkNavigationBarButtonLink.d.ts
  packages/bpk-component-navigation-bar/src/BpkNavigationBarIconButton.d.ts
  packages/bpk-component-navigation-bar/src/__snapshots__/BpkNavigationBar-test.tsx.snap
  packages/bpk-component-navigation-bar/src/themeAttributes.d.ts
Labels: minor

#3404 [LOOM-1305][BpkConfigurableNudger] Remove unused styling
  packages/bpk-component-nudger/src/BpkConfigurableNudger.tsx
  packages/bpk-component-nudger/src/BpkNudger.module.scss
  packages/bpk-component-nudger/src/__snapshots__/BpkNudger-test.tsx.snap
Labels: patch

#3410 LOOM-1306 BpkPaginationNudger Class 2 Overrides
  packages/bpk-component-pagination/src/BpkPaginationNudger.js
  packages/bpk-component-pagination/src/BpkPaginationNudger.module.scss
  packages/bpk-component-pagination/src/__snapshots__/BpkPaginationNudger-test.js.snap
Labels: minor

#3408 [LOOM-1296][withOpenEvents]: Place `openable` styling within BpkInput
  .eslintrc
  packages/bpk-component-datepicker/src/__snapshots__/BpkDatepicker-test.tsx.snap
  packages/bpk-component-input/src/BpkInput.module.scss
  packages/bpk-component-input/src/__snapshots__/withOpenEvents-test.tsx.snap
  packages/bpk-component-input/src/withOpenEvents.tsx
Labels: patch

#3413 [NOJIRA][chore]: ensure that icon dir is clean before copy
  gulpfile.js/bpk-component-icon/gulpfile.babel.js
  package-lock.json
Labels: patch

#3415 [LOOM-1306][BpkPaginationNudget]: Remove customised padding values
  packages/bpk-component-pagination/src/BpkPaginationNudger.js
  packages/bpk-component-pagination/src/BpkPaginationNudger.module.scss
  packages/bpk-component-pagination/src/__snapshots__/BpkPaginationNudger-test.js.snap
Labels: patch

#3414 [LOOM-1297][BpkSpinner]: Migrate to ts
  packages/bpk-component-image/src/BpkBackgroundImage.tsx
  packages/bpk-component-image/src/BpkImage.tsx
  packages/bpk-component-spinner/index.d.ts
  packages/bpk-component-spinner/index.ts
  packages/bpk-component-spinner/src/BpkExtraLargeSpinner.d.ts
  packages/bpk-component-spinner/src/BpkExtraLargeSpinner.tsx
  packages/bpk-component-spinner/src/BpkLargeSpinner.d.ts
  packages/bpk-component-spinner/src/BpkLargeSpinner.tsx
  packages/bpk-component-spinner/src/BpkSpinner.d.ts
  packages/bpk-component-spinner/src/BpkSpinner.tsx
  packages/bpk-component-spinner/src/spinnerTypes.ts
  packages/bpk-component-spinner/src/themeAttributes.ts
Labels: patch

#3402 [ZOOT-1102][BpkDialogInner]: Adds optional aria-modal to the dialog
  packages/bpk-component-dialog/src/BpkDialog-test.tsx
  packages/bpk-component-dialog/src/BpkDialogInner.tsx
  packages/bpk-component-dialog/src/__snapshots__/BpkDialog-test.tsx.snap
  packages/bpk-component-dialog/src/accessibility-test.tsx
  packages/bpk-component-dialog/src/common-types.d.ts
  packages/bpk-component-dialog/src/common-types.ts
  packages/package-lock.json
Labels: patch

#3419 [NO JIRA] [maintenance]: Update dist clean command as we never had rimraf
  package.json
Labels: skip-changelog

#3412 [LOOM-1297][BpkLoadingButton]: migrate to bpkbutton v2 & adopt ts in loading button
  packages/bpk-component-loading-button/src/BpkLoadingButton.module.scss
  packages/bpk-component-loading-button/src/BpkLoadingButton.tsx
  packages/bpk-component-loading-button/src/__snapshots__/BpkLoadingButton-test.js.snap
Labels: patch

#3424 [NoJira] fix the mixins vars
  packages/bpk-mixins/_forms.scss
Labels: patch

#3418 LOOM-1309 BpkPrice Class 2 Overrides
  packages/bpk-component-price/src/BpkPrice.js
  packages/bpk-component-price/src/BpkPrice.module.scss
  packages/bpk-component-price/src/__snapshots__/BpkPrice-test.js.snap
Labels: minor

#3420 [NoJIra][BpkModal] Update modal stories to tsx and add visual tests
  examples/bpk-component-modal/examples.tsx
  examples/bpk-component-modal/stories.tsx
Labels: patch

#3426 [Loom-1311][BpkScrollableCalendar] Class2 style fix
  packages/bpk-component-scrollable-calendar/src/BpkScrollableCalendarGrid.module.scss
  packages/bpk-component-scrollable-calendar/src/BpkScrollableCalendarGrid.tsx
  packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendar-test.tsx.snap
  packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendarGrid-test.tsx.snap
  packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendarGridList-test.tsx.snap
Labels: patch

#3406 Revert "Revert "[LOOM-1278][BpkBarChart] Class 2 Fix Remove unused classname prop""
  packages/bpk-component-barchart/src/BpkBarchart-test.js
  packages/bpk-component-barchart/src/BpkBarchart.js
  packages/bpk-component-barchart/src/__snapshots__/BpkBarchart-test.js.snap
Labels: DON'T MERGE, major

#3368 Luna 1326: Changes BpkSlider base library for mobile accessibility
  .eslintrc
  examples/bpk-component-slider/examples.js
  examples/bpk-component-slider/stories.js
  packages/bpk-component-slider/README.md
  packages/bpk-component-slider/index.d.ts
  packages/bpk-component-slider/src/BpkSlider-test.tsx
  packages/bpk-component-slider/src/BpkSlider.d.ts
  packages/bpk-component-slider/src/BpkSlider.module.scss
  packages/bpk-component-slider/src/BpkSlider.tsx
  packages/bpk-component-slider/src/__snapshots__/BpkSlider-test.tsx.snap
  packages/bpk-component-slider/src/accessibility-test.tsx
  packages/package-lock.json
  packages/package.json
Labels: DON'T MERGE, major

#3429 [LOOM-1312] [BpkScrollableCalendarGridList] Moved className to existing wrapper div
  packages/bpk-component-scrollable-calendar/src/BpkScrollableCalendarGridList.module.scss
  packages/bpk-component-scrollable-calendar/src/BpkScrollableCalendarGridList.tsx
  packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendar-test.tsx.snap
  packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendarGridList-test.tsx.snap
Labels: patch

#3430 [NOJIRA][BpkLoadingButton|BpkCloseButton]: fix loading console errors
  packages/bpk-component-close-button/src/BpkCloseButton-test.js
  packages/bpk-component-close-button/src/BpkCloseButton.js
  packages/bpk-component-loading-button/src/BpkLoadingButton-test.js
  packages/bpk-component-loading-button/src/BpkLoadingButton.tsx
Labels: patch

#3431 [NOJIRA][internal]: Add danger rule for console.error messages during testing
  .github/workflows/_build.yml
  dangerfile.ts
  package-lock.json
  package.json
Labels: enhancement, skip-changelog

#3427 [IRN-5039] BottomSheet supports aria-label
  examples/bpk-component-bottom-sheet/examples.tsx
  packages/bpk-component-bottom-sheet/src/BpkBottomSheet-test.tsx
  packages/bpk-component-bottom-sheet/src/BpkBottomSheet.tsx
  packages/bpk-react-utils/src/BpkDialogWrapper/BpkDialogWrapper-test.tsx
  packages/bpk-react-utils/src/BpkDialogWrapper/BpkDialogWrapper.tsx
  packages/bpk-react-utils/src/BpkDialogWrapper/accessibility-test.tsx
Labels: minor

#3432 [LOOM-1310][BpkRating]: remove className usage on BpkText & migrate to TS
  package-lock.json
  package.json
  packages/bpk-component-rating/index.ts
  packages/bpk-component-rating/src/BpkRating-test.tsx
  packages/bpk-component-rating/src/BpkRating.module.scss
  packages/bpk-component-rating/src/BpkRating.tsx
  packages/bpk-component-rating/src/__snapshots__/BpkRating-test.js.snap
  packages/bpk-component-rating/src/__snapshots__/BpkRating-test.tsx.snap
  packages/bpk-component-rating/src/accessibility-test.tsx
  packages/bpk-component-rating/src/common-types.ts
Labels: minor

#3433 [LOOM-1310][BpkRating]: correct letter-spacing in bpk rating
  packages/bpk-component-rating/src/BpkRating.tsx
  packages/bpk-component-rating/src/__snapshots__/BpkRating-test.tsx.snap
Labels: minor

#3434 [NoJira][BpkSpinner] Type SpinnerType fixes
  examples/bpk-component-spinner/SpinnerLayout.tsx
  examples/bpk-component-spinner/examples.tsx
  examples/bpk-component-spinner/stories.ts
  packages/bpk-component-spinner/src/BpkExtraLargeSpinner.d.ts
  packages/bpk-component-spinner/src/BpkExtraLargeSpinner.tsx
  packages/bpk-component-spinner/src/BpkLargeSpinner.d.ts
  packages/bpk-component-spinner/src/BpkLargeSpinner.tsx
  packages/bpk-component-spinner/src/BpkSpinner.d.ts
  packages/bpk-component-spinner/src/BpkSpinner.tsx
  packages/bpk-component-spinner/src/spinnerTypes.ts
Labels: patch

#3435 [WALL-1371][BpkText] Add Larken TextStyles to Backpack
  .storybook/preview.tsx
  examples/bpk-component-text/examples.js
  examples/bpk-component-text/stories.js
  package-lock.json
  package.json
  packages/bpk-component-text/src/BpkText-test.tsx
  packages/bpk-component-text/src/BpkText.module.scss
  packages/bpk-component-text/src/BpkText.tsx
  packages/bpk-component-text/src/__snapshots__/BpkText-test.tsx.snap
  packages/bpk-mixins/_typography.scss
  packages/bpk-stylesheets/README.md
  packages/bpk-stylesheets/larken.js
  packages/bpk-stylesheets/larken.scss
  packages/package-lock.json
  packages/package.json
Labels: minor

#3444 LOOM-1362 BpkBannerAlertInner Class 2 Overrides
  packages/bpk-component-banner-alert/src/BpkBannerAlertInner.tsx
  packages/bpk-component-banner-alert/src/__snapshots__/BpkBannerAlert-test.tsx.snap
  packages/bpk-component-banner-alert/src/__snapshots__/BpkBannerAlertDismissable-test.tsx.snap
  packages/bpk-component-banner-alert/src/__snapshots__/BpkBannerAlertInner-test.tsx.snap
  packages/bpk-component-banner-alert/src/__snapshots__/withBannerAlertState-test.tsx.snap
Labels: minor

#3440 [LOOM-1319][BpkDividedCard]: Remove className from BpkCard
  packages/bpk-component-card/src/BpkCard.module.scss
  packages/bpk-component-card/src/BpkCard.tsx
  packages/bpk-component-card/src/BpkCardWrapper.tsx
  packages/bpk-component-card/src/BpkDividedCard.module.scss
  packages/bpk-component-card/src/BpkDividedCard.tsx
  packages/bpk-component-card/src/CardContext.ts
  packages/bpk-component-card/src/__snapshots__/BpkDividedCard-test.tsx.snap
Labels: minor

#3449 [NoJira][BpkNavigationBar] new storybook visual test for navbar with custom title
  examples/bpk-component-navigation-bar/examples.js
  examples/bpk-component-navigation-bar/stories.js
Labels: enhancement, patch

#3454 LOOM-1365 BpkDialogInner
  packages/bpk-component-dialog/src/BpkDialogInner.module.scss
  packages/bpk-component-dialog/src/BpkDialogInner.tsx
  packages/bpk-component-dialog/src/__snapshots__/BpkDialog-test.tsx.snap
Labels: minor

#3457 [LOOM-1361] [BpkAutoSuggestSuggestion] Added wrapper div around Icon for className prop
  packages/bpk-component-autosuggest/src/BpkAutosuggest.module.scss
  packages/bpk-component-autosuggest/src/BpkAutosuggestSuggestion.js
  packages/bpk-component-autosuggest/src/__snapshots__/BpkAutosuggestSuggestion-test.js.snap
Labels: patch

#3450 [maintenance][ARGG-1144]: Move Percy later in the CI as last step
  .github/workflows/_build.yml
Labels: skip-changelog

#3445 [NO JIRA]: Update release CI to move supernova
  .github/workflows/release.yml
Labels: skip-changelog

#3459 [BpkPopover]: Fix popover z-index for rendering over content
  packages/bpk-component-popover/src/BpkPopover.module.scss
  packages/bpk-component-popover/src/BpkPopover.tsx
Labels: patch

#3455 [ARGG-1085][BpkPopover] Update popover design
  examples/bpk-component-popover/examples.js
  examples/bpk-component-popover/stories.js
  packages/bpk-component-popover/README.md
  packages/bpk-component-popover/src/BpkPopover-test.tsx
  packages/bpk-component-popover/src/BpkPopover.module.scss
  packages/bpk-component-popover/src/BpkPopover.tsx
Labels: minor

#3446 [LOOM-1361] [BpkAutosuggestSuggestion] Added interaction visual test and default open for All test
  .storybook/main.ts
  examples/bpk-component-autosuggest/examples.js
  examples/bpk-component-autosuggest/stories.js
  package-lock.json
  package.json
Labels: skip-changelog

#3461 [BpkNudger] Fix accessibility issue
  packages/bpk-component-nudger/src/BpkConfigurableNudger.tsx
  packages/bpk-component-nudger/src/__snapshots__/BpkNudger-test.tsx.snap
Labels: patch, Accessibility

#3453 [LOOM-1364][BpkSaveButton]: remove className from HeartIcons, refactor
  packages/bpk-component-card-button/src/BpkSaveButton.module.scss
  packages/bpk-component-card-button/src/BpkSaveButton.tsx
  packages/bpk-component-card-button/src/__snapshots__/BpkSaveButton-test.tsx.snap
Labels: minor

#3447 [LOOM-1300][BpkModalInner] Style 2 fixes
  .eslintrc
  packages/bpk-component-close-button/src/BpkCloseButton.module.scss
  packages/bpk-component-modal/src/BpkModalInner.module.scss
  packages/bpk-component-modal/src/BpkModalInner.tsx
  packages/bpk-component-modal/src/__snapshots__/BpkModal-test.tsx.snap
  packages/bpk-component-modal/src/__snapshots__/BpkModalInner-test.tsx.snap
Labels: patch

#3463 [NOJIRA][BpkBreakpoint]: Bug fix initial incorrect value of isClient on client rendered applications
  packages/bpk-component-breakpoint/src/BpkBreakpoint-test.tsx
  packages/bpk-component-breakpoint/src/BpkBreakpoint.tsx
Labels: patch

#3462 [WALL-1371][BpkText] Add the Noto fallbacks for the Larken font
  examples/bpk-component-text/examples.js
  examples/bpk-component-text/stories.js
  package-lock.json
  package.json
  packages/bpk-component-text/README.md
  packages/bpk-stylesheets/larken.scss
  packages/package-lock.json
  packages/package.json
Labels: minor

#3464 [maintainence][BpkModalV2] Add Visual Snapshots
  examples/bpk-component-modal-v2/examples.tsx
  examples/bpk-component-modal-v2/stories.tsx
Labels: patch

#3465 [NOJIRA][BpkFloatingNotification]: Fix CTA position
  examples/bpk-component-floating-notification/examples.tsx
  packages/bpk-component-floating-notification/src/BpkFloatingNotification.module.scss
  packages/bpk-component-floating-notification/src/BpkFloatingNotification.tsx
  packages/bpk-component-floating-notification/src/__snapshots__/BpkFloatingNotification-test.tsx.snap
Labels: patch

#3466 [LOOM-1370][BpkPaginationPage] Replace BpkButton in BpkPaginationPage
  packages/bpk-component-pagination/src/BpkPaginationPage.js
  packages/bpk-component-pagination/src/BpkPaginationPage.module.scss
Labels: patch

#3468 [LOOM-1375][BpkIcon] eslint Override for ComposedComponent in BpkIcon
  .eslintrc
  packages/bpk-component-icon/src/classNameModifierHOCFactory.tsx
Labels: patch

#3469 [LOOM-1374][BpkDescriptionList] - Typescript and Class2 style fixes.
  packages/bpk-component-description-list/index.ts
  packages/bpk-component-description-list/src/BpkDescriptionDetails-test.tsx
  packages/bpk-component-description-list/src/BpkDescriptionDetails.js
  packages/bpk-component-description-list/src/BpkDescriptionDetails.tsx
  packages/bpk-component-description-list/src/BpkDescriptionList-test.tsx
  packages/bpk-component-description-list/src/BpkDescriptionList.tsx
  packages/bpk-component-description-list/src/BpkDescriptionTerm-test.tsx
  packages/bpk-component-description-list/src/BpkDescriptionTerm.tsx
  packages/bpk-component-description-list/src/__snapshots__/BpkDescriptionDetails-test.tsx.snap
  packages/bpk-component-description-list/src/__snapshots__/BpkDescriptionList-test.tsx.snap
  packages/bpk-component-description-list/src/__snapshots__/BpkDescriptionTerm-test.tsx.snap
  packages/bpk-component-description-list/src/accessibility-test.tsx
Labels: patch

#3473 Revert "Bump css-loader from 6.10.0 to 7.1.1"
  package-lock.json
  package.json
Labels: skip-changelog

#3472 [NO JIRA][BpkPopover]: Fix popover container classname
  packages/bpk-component-popover/src/BpkPopover.module.scss
Labels: patch

#3471 [BpkDialog]: Fix optional modal prop
  packages/bpk-component-dialog/src/common-types.ts
Labels: patch

#3479 [BD-8430][BpkHorizontalNav, BpkMobileScrollContainer, withScrim] Resolve reflow impact
  packages/bpk-component-horizontal-nav/src/BpkHorizontalNav.js
  packages/bpk-component-mobile-scroll-container/src/BpkMobileScrollContainer.js
  packages/bpk-scrim-utils/src/withScrim-test.tsx
  packages/bpk-scrim-utils/src/withScrim.tsx
Labels: minor
