Repository Skyscanner/backpack, pull requests merged in 2024-02, with the labels that each got.

#3206 [NO JIRA]: Update build caching key naming to account for stories updates
  .github/workflows/_build.yml
  .github/workflows/main.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
Labels: skip-changelog

#3220 DTO-4733 RTL Languages Backpack Rating Fix
  packages/bpk-component-rating/src/BpkRating.module.css
  packages/bpk-component-rating/src/BpkRating.module.scss
Labels: patch

#3221 [NO-JIRA] Migrate Floating Notification component to TS
  packages/bpk-component-floating-notification/index.ts
  packages/bpk-component-floating-notification/src/BpkFloatingNotification-test.tsx
  packages/bpk-component-floating-notification/src/BpkFloatingNotification.d.ts
  packages/bpk-component-floating-notification/src/BpkFloatingNotification.tsx
  packages/bpk-component-floating-notification/src/__snapshots__/BpkFloatingNotification-test.tsx.snap
  packages/bpk-component-floating-notification/src/accessibility-test.tsx
Labels: minor

#3232 LUNA-1234: iOS BpkSwapButton fix
  examples/bpk-component-swap-button/examples.js
  packages/bpk-component-swap-button/src/BpkSwapButton.module.css
  packages/bpk-component-swap-button/src/BpkSwapButton.module.scss
  packages/bpk-component-swap-button/src/BpkSwapButton.tsx
  packages/bpk-component-swap-button/src/__snapshots__/BpkSwapButton-test.tsx.snap
Labels: patch

#3155 [ARGG-794][BpkDataTable] Remove deprecated props in BpkDataTable and migrate to TS
  examples/bpk-component-datatable/examples.tsx
  examples/bpk-component-datatable/stories.ts
  packages/bpk-component-datatable/README.md
  packages/bpk-component-datatable/docs/migrating.md
  packages/bpk-component-datatable/index.ts
  packages/bpk-component-datatable/src/BpkDataTable-test.tsx
  packages/bpk-component-datatable/src/BpkDataTable.tsx
  packages/bpk-component-datatable/src/BpkDataTableColumn.js
  packages/bpk-component-datatable/src/BpkDataTableColumn.module.css
  packages/bpk-component-datatable/src/BpkDataTableHeader-test.tsx
  packages/bpk-component-datatable/src/BpkDataTableHeader.tsx
  packages/bpk-component-datatable/src/__snapshots__/BpkDataTable-test.tsx.snap
  packages/bpk-component-datatable/src/__snapshots__/BpkDataTableHeader-test.tsx.snap
  packages/bpk-component-datatable/src/accessibility-test.tsx
  packages/bpk-component-datatable/src/common-types.js
  packages/bpk-component-datatable/src/common-types.ts
  packages/bpk-component-datatable/src/hasChildrenOfType.js
  packages/bpk-component-datatable/src/sort-types.js
  packages/bpk-component-datatable/src/utils.js
  packages/bpk-component-datatable/src/utils.ts
Labels: major

#3156 [DTO-4950][BpkBadge] Clean up & Make BpkBadgeV2 the default
  examples/bpk-component-badge-v2/BadgeLayout.js
  examples/bpk-component-badge-v2/BpkBadgeLayout.module.css
  examples/bpk-component-badge-v2/BpkBadgeLayout.module.scss
  examples/bpk-component-badge-v2/examples.js
  examples/bpk-component-badge-v2/stories.js
  packages/bpk-component-badge/index.ts
  packages/bpk-component-badge/src/BpkBadge.module.css
  packages/bpk-component-badge/src/BpkBadgeV2/BpkBadge-test.tsx
  packages/bpk-component-badge/src/BpkBadgeV2/BpkBadge.d.ts
  packages/bpk-component-badge/src/BpkBadgeV2/BpkBadge.module.css
  packages/bpk-component-badge/src/BpkBadgeV2/BpkBadge.module.scss
  packages/bpk-component-badge/src/BpkBadgeV2/BpkBadge.tsx
  packages/bpk-component-badge/src/BpkBadgeV2/README.md
  packages/bpk-component-badge/src/BpkBadgeV2/__snapshots__/BpkBadge-test.tsx.snap
  packages/bpk-component-badge/src/BpkBadgeV2/accessibility-test.tsx
  packages/bpk-mixins/src/mixins/_badges.scss
Labels: major

#3244 [NOJIRA]: Import compiled stylesheet
  packages/bpk-stylesheets/base.css
  packages/bpk-stylesheets/index.js
  packages/bpk-stylesheets/index.scss
Labels: patch

#3248 [LOOM-1221][BpkButton]: Add fullWidth prop to BpkButton
  examples/bpk-component-button/examples.js
  examples/bpk-component-button/stories.js
  packages/bpk-component-button/README.md
  packages/bpk-component-button/src/BpkButtonV2/BpkButton-test.tsx
  packages/bpk-component-button/src/BpkButtonV2/BpkButton.d.ts
  packages/bpk-component-button/src/BpkButtonV2/BpkButton.module.scss
  packages/bpk-component-button/src/BpkButtonV2/BpkButton.tsx
  packages/bpk-component-button/src/BpkButtonV2/common-types.d.ts
  packages/bpk-component-button/src/BpkButtonV2/common-types.tsx
  packages/bpk-mixins/_buttons.scss
Labels: minor

#3259 [ARGG-1036] [BpkSectionHeader] Fix section header vertical padding
  packages/bpk-component-section-header/src/BpkSectionHeader.module.scss
  packages/bpk-component-section-header/src/BpkSectionHeader.tsx
  packages/bpk-component-section-header/src/__snapshots__/BpkSectionHeader-test.tsx.snap
Labels: patch

#3258 [DTO-4950][BpkBadge] Remove BpkBadgeV2 type declarations
  .github/pull_request_template.md
  packages/bpk-component-badge/index.d.ts
Labels: patch
