Repository Skyscanner/backpack, pull requests merged in 2024-07, with the labels that each got.

#3509 [COR-177][JourneyArrow] Add new JourneyArrow component with stop count
  examples/bpk-component-journey-arrow/example.tsx
  examples/bpk-component-journey-arrow/stories.tsx
  packages/bpk-component-journey-arrow/README.md
  packages/bpk-component-journey-arrow/index.ts
  packages/bpk-component-journey-arrow/src/BpkJourneyArrow-test.tsx
  packages/bpk-component-journey-arrow/src/BpkJourneyArrow.module.scss
  packages/bpk-component-journey-arrow/src/BpkJourneyArrow.tsx
  packages/bpk-component-journey-arrow/src/accessibility-test.tsx
Labels: minor

#3523 [NO JIRA][BpkPopover]: Check for onClick property in the target
  packages/bpk-component-popover/src/BpkPopover.tsx
Labels: patch

#3528 [BD-7461][BpkIconMarker] Make the icon to support RTL
  packages/bpk-component-map/src/BpkIconMarker.module.scss
Labels: patch

#3526 [Luna-1372][BpkAccordion] Remove description filter
  packages/bpk-component-accordion/src/BpkAccordion.js
  packages/bpk-component-accordion/src/BpkAccordionItem.js
  packages/bpk-component-accordion/src/__snapshots__/BpkAccordion-test.js.snap
  packages/bpk-component-accordion/src/__snapshots__/BpkAccordionItem-test.js.snap
  packages/bpk-component-accordion/src/__snapshots__/withAccordionItemState-test.js.snap
  packages/bpk-component-accordion/src/__snapshots__/withSingleItemAccordionState-test.js.snap
Labels: patch

#3520 [BD-8573][BpkCarousel][BpkMobileScrollContainer] Resolve force reflow issues causing by carousel utils and scroll container
  packages/bpk-component-carousel/src/utils.test.tsx
  packages/bpk-component-carousel/src/utils.tsx
  packages/bpk-component-mobile-scroll-container/src/BpkMobileScrollContainer.js
Labels: minor

#3527 [NO JIRA][BpkPopover]: Reinstate renderTarget prop for rendering in DOM at specific location
  examples/bpk-component-popover/examples.js
  examples/bpk-component-popover/stories.js
  packages/bpk-component-popover/src/BpkPopover.tsx
Labels: patch

#3530 [NO-JIRA] [BpkSegmentedControl] RTL fix
  packages/bpk-component-segmented-control/src/BpkSegmentedControl.module.scss
Labels: patch

#3518 [QUAR-425] [BpkInsetBanner] Add component
  examples/bpk-component-inset-banner/examples.tsx
  examples/bpk-component-inset-banner/stories.ts
  packages/bpk-component-inset-banner/README.md
  packages/bpk-component-inset-banner/index.ts
  packages/bpk-component-inset-banner/src/BpkInsetBanner-test.tsx
  packages/bpk-component-inset-banner/src/BpkInsetBanner.module.scss
  packages/bpk-component-inset-banner/src/BpkInsetBanner.tsx
  packages/bpk-component-inset-banner/src/accessibility-test.tsx
Labels: minor

#3536 [ARGG-1161][Portal]: Deprecate the Backpack Portal component
  packages/bpk-react-utils/README.md
  packages/bpk-react-utils/docs/portal-migration.md
  packages/bpk-react-utils/src/Portal.tsx
Labels: minor

#3537 [COR-251] [BpkJourneyArrow] Remove minimum width
  packages/bpk-component-journey-arrow/src/BpkJourneyArrow.module.scss
Labels: patch

#3539 [LUNA-1675]: [BpkSegmentedControls] fixes focus styling
  packages/bpk-component-segmented-control/src/BpkSegmentedControl.module.scss
Labels: patch

#3522 [ARGG-1159][BpkModal]: Remove portal from modal
  examples/bpk-component-modal/examples.tsx
  packages/bpk-component-datepicker/src/BpkDatepicker.tsx
  packages/bpk-component-modal/src/BpkModal-test.tsx
  packages/bpk-component-modal/src/BpkModal.tsx
  packages/bpk-component-modal/src/__snapshots__/BpkModal-test.tsx.snap
  packages/bpk-component-modal/src/accessibility-test.tsx
Labels: patch

#3541 [NOJIRA][maintenance]: remove theme toggle from storybook
  .storybook/preview.tsx
Labels: skip-changelog

#3508 [ARGG-1158][BpkDialog]: Migrate Dialog to not use Portal
  examples/bpk-component-dialog/examples.js
  examples/bpk-component-dialog/examples.tsx
  examples/bpk-component-dialog/stories.js
  examples/bpk-component-dialog/stories.tsx
  packages/bpk-component-dialog/src/BpkDialog-test.tsx
  packages/bpk-component-dialog/src/BpkDialog.tsx
  packages/bpk-component-dialog/src/__snapshots__/BpkDialog-test.tsx.snap
  packages/bpk-component-dialog/src/accessibility-test.tsx
Labels: patch

#3543 [NO-JIRA]: [BpkSegmentedControls] Fix rtl border radius issue
  packages/bpk-component-segmented-control/src/BpkSegmentedControl.module.scss
Labels: patch

#3540 [LOOM-1525] - Refactor Nudger remove readonly attribute from input and Emit native events from buttons
  packages/bpk-component-nudger/src/BpkConfigurableNudger.tsx
  packages/bpk-component-nudger/src/__snapshots__/BpkNudger-test.tsx.snap
  packages/bpk-component-nudger/src/common-types.ts
  packages/bpk-react-utils/index.ts
  packages/bpk-react-utils/src/nativeEventHandler-test.tsx
  packages/bpk-react-utils/src/nativeEventHandler.ts
Labels: minor

#3550 [NO JIRA][BpkImage]: Update image radius to 12px
  packages/bpk-component-image/src/BpkImage.module.scss
Labels: minor

#3551 [LUNA-1725][BpkFloatingNotification] Fixing FloatingNotification to viewport
  packages/bpk-component-floating-notification/src/BpkFloatingNotification.module.scss
Labels: patch

#3554 Revert "[BD-8573][BpkCarousel][BpkMobileScrollContainer] Resolve force reflow issues causing by carousel utils and scroll container"
  packages/bpk-component-carousel/src/utils.test.tsx
  packages/bpk-component-carousel/src/utils.tsx
  packages/bpk-component-mobile-scroll-container/src/BpkMobileScrollContainer.js
Labels: minor

#3552 [NOJIRA][BpkMap] Fix @react-google-maps/api to latest version
  packages/package-lock.json
  packages/package.json
Labels: minor

#3553 [WALL-2135][BpkAccordion] Fix accordion transition animation
  packages/bpk-component-accordion/src/BpkAccordionItem.js
  packages/bpk-component-accordion/src/BpkAccordionItem.module.scss
  packages/bpk-component-accordion/src/__snapshots__/BpkAccordionItem-test.js.snap
  packages/bpk-component-accordion/src/__snapshots__/withAccordionItemState-test.js.snap
Labels: javascript, patch

#3558 Revert "[ARGG-1161][Portal]: Deprecate the Backpack Portal component"
  packages/bpk-react-utils/README.md
  packages/bpk-react-utils/docs/portal-migration.md
  packages/bpk-react-utils/src/Portal.tsx
Labels: patch

#3559 [WALL-2135]{BpkAccordion] Fix accordion wothout divider
  examples/bpk-component-accordion/examples.js
  examples/bpk-component-accordion/stories.js
  packages/bpk-component-accordion/src/BpkAccordionItem.js
  packages/bpk-component-accordion/src/BpkAccordionItem.module.scss
  packages/bpk-component-accordion/src/__snapshots__/BpkAccordionItem-test.js.snap
  packages/bpk-component-accordion/src/__snapshots__/withAccordionItemState-test.js.snap
Labels: javascript, patch

#3564 LOOM-1521: add name props for input
  packages/bpk-component-split-input/src/BpkInputField.js
  packages/bpk-component-split-input/src/BpkSplitInput.js
  packages/bpk-component-split-input/src/__snapshots__/BpkSplitInput-test.js.snap
Labels: enhancement, minor

#3566 [LOOM-1531] Add form tests for form components
  packages/bpk-component-checkbox/src/form-test.js
  packages/bpk-component-input/src/form-test.tsx
  packages/bpk-component-nudger/src/form-test.tsx
  packages/bpk-component-phone-input/src/form-test.js
  packages/bpk-component-radio/src/form-test.js
  packages/bpk-component-select/src/form-test.js
  packages/bpk-component-switch/src/form-test.js
Labels: skip-changelog
