Repository Skyscanner/backpack, pull requests merged in 2025-02, with the labels that each got.

#3735 [THES-687] update bpk-svgs version
  package-lock.json
  package.json
  packages/package-lock.json
  packages/package.json
Labels: minor

#3732 [QUAR-497] [BpkInsetBanner] Add CTA button & popover
  examples/bpk-component-inset-banner/examples.tsx
  examples/bpk-component-inset-banner/stories.ts
  packages/bpk-component-inset-banner/README.md
  packages/bpk-component-inset-banner/src/BpkInsetBanner-test.tsx
  packages/bpk-component-inset-banner/src/BpkInsetBanner.module.scss
  packages/bpk-component-inset-banner/src/BpkInsetBanner.tsx
  packages/bpk-component-inset-banner/src/accessibility-test.tsx
Labels: minor

#3737 [BpkSwitch] Adjust focus behaviour
  packages/bpk-component-switch/src/BpkSwitch.module.scss
Labels: patch

#3741 [BD-9310][BpkMobileScrollContainer] Remove unused scroll indicators
  packages/bpk-component-mobile-scroll-container/src/BpkMobileScrollContainer.module.scss
Labels: minor

#3742 [BD-9345][BpkPrice] Add a new icon property to BpkPrice
  examples/bpk-component-price/examples.js
  examples/bpk-component-price/stories.js
  packages/bpk-component-price/README.md
  packages/bpk-component-price/src/BpkPrice-test.js
  packages/bpk-component-price/src/BpkPrice.js
  packages/bpk-component-price/src/BpkPrice.module.scss
  packages/bpk-component-price/src/__snapshots__/BpkPrice-test.js.snap
Labels: minor

#3749 [NOJIRA] install and migrate to css-loader@v7
  .storybook/webpack.config.js
  package-lock.json
  package.json
  packages/bpk-stylesheets/webpack.config.babel.js
Labels: patch

#3752 [ACC-632][BpkCalendarGrid]: Fix accessibility issue - grid has no accessible name
  examples/bpk-component-calendar/examples.js
  packages/bpk-component-calendar/src/BpkCalendarGrid-test.tsx
  packages/bpk-component-calendar/src/BpkCalendarGrid.tsx
  packages/bpk-component-calendar/src/__snapshots__/BpkCalendarContainer-test.tsx.snap
  packages/bpk-component-calendar/src/__snapshots__/BpkCalendarGrid-test.tsx.snap
  packages/bpk-component-scrollable-calendar/src/BpkScrollableCalendarGrid.tsx
  packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendar-test.tsx.snap
  packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendarGrid-test.tsx.snap
  packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendarGridList-test.tsx.snap
Labels: patch, Accessibility

#3750 [BD-9310][BpkMobileScrollContainer] Optimize the use of debounce for compatibility
  packages/bpk-component-mobile-scroll-container/src/BpkMobileScrollContainer.tsx
Labels: patch

#3751 [BD-9484][BpkInfoBannerExpandable] Fix an a11y issue
  packages/bpk-component-info-banner/src/BpkInfoBanner-test.tsx
  packages/bpk-component-info-banner/src/BpkInfoBanner.module.scss
  packages/bpk-component-info-banner/src/BpkInfoBannerExpandable-test.tsx
  packages/bpk-component-info-banner/src/BpkInfoBannerInner.tsx
  packages/bpk-component-info-banner/src/__snapshots__/BpkInfoBanner-test.tsx.snap
  packages/bpk-component-info-banner/src/__snapshots__/BpkInfoBannerDismissable-test.tsx.snap
  packages/bpk-component-info-banner/src/__snapshots__/BpkInfoBannerInner-test.tsx.snap
  packages/bpk-component-info-banner/src/__snapshots__/withBannerAlertState-test.tsx.snap
  packages/bpk-component-info-banner/src/withBannerAlertState-test.tsx
Labels: minor, Accessibility

#3740 [LOOM-2050]: Updating docs for different build tools usage
  packages/bpk-stylesheets/README.md
Labels: skip-changelog
