Repository Skyscanner/backpack, pull requests merged in 2025-05, with the labels that each got.

#3817 [NoJira][BpkLink] Remove the underline when bpklink-implicit is clicked.
  packages/bpk-mixins/_typography.scss
Labels: patch

#3816 [CAPY-1169][BpkChipGroup]: Set Chip Group Nudgers edge threshold
  packages/bpk-component-chip-group/src/Nudger.tsx
Labels: patch

#3818 [BpkLink] Reimplement bpklink using gradient background.
  examples/bpk-component-link/examples.js
  examples/bpk-component-link/stories.js
  packages/bpk-component-breadcrumb/src/__snapshots__/BpkBreadcrumbItem-test.js.snap
  packages/bpk-component-grid-toggle/src/__snapshots__/BpkGridToggle-test.js.snap
  packages/bpk-component-link/src/BpkButtonLink.js
  packages/bpk-component-link/src/BpkLink.js
  packages/bpk-component-link/src/BpkLink.module.scss
  packages/bpk-component-link/src/__snapshots__/BpkButtonLink-test.js.snap
  packages/bpk-component-link/src/__snapshots__/BpkLink-test.js.snap
  packages/bpk-component-modal/src/__snapshots__/BpkModalInner-test.tsx.snap
  packages/bpk-component-navigation-bar/src/__snapshots__/BpkNavigationBarButtonLink-test.tsx.snap
  packages/bpk-component-rtl-toggle/src/__snapshots__/BpkRtlToggle-test.tsx.snap
  packages/bpk-mixins/_typography.scss
Labels: minor

#3819 [CAPY-1378][BpkImage]: Fixing bpk-background-image loading spinner position
  packages/bpk-component-image/src/BpkBackgroundImage.tsx
  packages/bpk-component-image/src/__snapshots__/BpkBackgroundImage-test.tsx.snap
Labels: patch

#3820 [NoJira][BpkLink] change underline offset to 1px
  packages/bpk-mixins/_typography.scss
Labels: patch

#3826 [NO-JIRA][maintenance]: Remove no longer required danger warning
  dangerfile.ts
Labels: skip-changelog

#3824 [CLOV-230][BpkTooltip]Fix arrow alignment
  packages/bpk-component-tooltip/src/BpkTooltip.tsx
Labels: patch

#3831 [NOJIRA][BpkMobileScrollContainer]expose onScroll
  packages/bpk-component-mobile-scroll-container/src/BpkMobileScrollContainer-test.tsx
  packages/bpk-component-mobile-scroll-container/src/BpkMobileScrollContainer.tsx
Labels: patch

#3834 [CAPY-1253][BpkNavigationTabGroup]: Prevent NavigationTabGroup selection when tab opens a new browser tab
  examples/bpk-component-navigation-tab-group/examples.tsx
  examples/bpk-component-navigation-tab-group/stories.tsx
  packages/bpk-component-navigation-tab-group/src/BpkNavigationTabGroup-test.tsx
  packages/bpk-component-navigation-tab-group/src/BpkNavigationTabGroup.tsx
Labels: patch

#3835 [BpkSegmentedControl] adjust role and add label prop
  packages/bpk-component-segmented-control/src/BpkSegmentedControl-test.tsx
  packages/bpk-component-segmented-control/src/BpkSegmentedControl.tsx
Labels: patch, Accessibility

#3837 [BpkSegmentedControl] Update Storybook and docs
  examples/bpk-component-segmented-control/examples.tsx
  packages/bpk-component-segmented-control/README.md
Labels: patch

#3836 [CLOV-239]BPK-rating-stars-Extralarge
  .eslintignore
  .prettierignore
  examples/bpk-component-icon/examples.js
  package-lock.json
  package.json
  packages/bpk-component-icon/all.tsx
  packages/bpk-component-star-rating/src/BpkStar.js
  packages/bpk-component-star-rating/src/BpkStar.module.scss
  packages/bpk-component-star-rating/src/__snapshots__/BpkStar-test.js.snap
  packages/bpk-component-star-rating/src/__snapshots__/BpkStarRating-test.js.snap
  packages/package-lock.json
  packages/package.json
Labels: minor

#3833 [BD-9804]Update RailChipGroup stickyChip behavior of BpkMultiSelectChipGroup on Mweb
  packages/bpk-component-chip-group/src/BpkChipGroup.module.scss
  packages/bpk-component-chip-group/src/BpkMultiSelectChipGroup-test.tsx
  packages/bpk-component-chip-group/src/BpkMultiSelectChipGroup.tsx
  packages/bpk-component-chip-group/src/BpkStickyChip-test.tsx
  packages/bpk-component-chip-group/src/BpkStickyChip.module.scss
  packages/bpk-component-chip-group/src/BpkStickyChip.tsx
Labels: minor

#3839 [NO JIRA]Tribble ExtraLarge Rename
  examples/bpk-component-icon/examples.js
  examples/bpk-component-icon/stories.js
Labels: patch

#3843 [Clover-199]Fix the vulnerability alert: Uncontrolled resource consumption in braces
  package-lock.json
  package.json
Labels: dependencies, minor

#3847 [BpkScrollableCalendarGrid] Adjust month heading from H1 to H2
  packages/bpk-component-scrollable-calendar/src/BpkScrollableCalendarGrid.tsx
  packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendar-test.tsx.snap
  packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendarGrid-test.tsx.snap
  packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendarGridList-test.tsx.snap
Labels: patch, Accessibility
