Repository Skyscanner/backpack, pull requests merged in 2025-01, with the labels that each got.

#3695 [WOM-5377][BpkComponentCalendar] Optimise date formatting for improved INP
  examples/bpk-component-calendar/examples.js
  packages/bpk-component-calendar/src/BpkCalendarDate.tsx
  packages/bpk-component-calendar/src/BpkCalendarGrid.tsx
  packages/bpk-component-calendar/src/BpkCalendarWeek-test.tsx
  packages/bpk-component-calendar/src/BpkCalendarWeek.tsx
  packages/bpk-component-calendar/src/composeCalendar.tsx
  packages/bpk-component-calendar/src/date-utils.ts
  packages/bpk-component-carousel/src/utils-test.tsx
  packages/bpk-react-utils/index.ts
  packages/bpk-react-utils/src/__mocks__/deferCallback.ts
  packages/bpk-react-utils/src/deferCallback-test.ts
  packages/bpk-react-utils/src/deferCallback.ts
  scripts/jest/setup.js
Labels: minor

#3700 [NO JIRA]: Update popover fallback to align with floating-ui
  packages/bpk-component-popover/index.d.ts
  packages/bpk-component-popover/src/BpkPopover.d.ts
  packages/bpk-component-popover/src/BpkPopover.tsx
  packages/bpk-component-popover/src/constants.d.ts
  packages/bpk-component-popover/src/themeAttributes.d.ts
Labels: patch

#3622 [NO JIRA]: Upgrade date-fns to support v4
  package-lock.json
  package.json
  packages/package-lock.json
  packages/package.json
Labels: minor

#3703 [LOOM-2014]: Update form element corner radii
  package-lock.json
  package.json
  packages/bpk-mixins/_forms.scss
  packages/package-lock.json
  packages/package.json
Labels: minor

#3707 [NO JIRA]: Update compliation of stylesheets
  package.json
  packages/bpk-stylesheets/webpack.config.babel.js
  scripts/transpilation/transform-js-scss-css-imports.js
Labels: patch

#3705 [Nojira] Support the rest type for BpkPopover
  packages/bpk-component-popover/src/BpkPopover.tsx
Labels: minor

#3699 [BpkCalendar] Accessibility roles
  packages/bpk-component-calendar/src/BpkCalendarContainer-test.tsx
  packages/bpk-component-calendar/src/BpkCalendarDate.tsx
  packages/bpk-component-calendar/src/BpkCalendarGrid.tsx
  packages/bpk-component-calendar/src/BpkCalendarWeek.tsx
  packages/bpk-component-calendar/src/__snapshots__/BpkCalendarContainer-test.tsx.snap
  packages/bpk-component-calendar/src/__snapshots__/BpkCalendarDate-test.tsx.snap
  packages/bpk-component-calendar/src/__snapshots__/BpkCalendarGrid-test.tsx.snap
  packages/bpk-component-calendar/src/__snapshots__/BpkCalendarWeek-test.tsx.snap
  packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendar-test.tsx.snap
  packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendarDate-test.tsx.snap
  packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendarGrid-test.tsx.snap
  packages/bpk-component-scrollable-calendar/src/__snapshots__/BpkScrollableCalendarGridList-test.tsx.snap
Labels: patch

#3716 [NoJira] [BpkSlider] Update the radix deps
  packages/package-lock.json
  packages/package.json
Labels: dependencies, patch

#3577 [LOOM-2025][BpkAccordion]: Update padding between title and expand icon to be 8px
  packages/bpk-component-accordion/src/BpkAccordionItem.module.scss
Labels: patch

#3725 [ST-6228] [BpkSlider] Pin react-slider to version that still supports React 17
  packages/package-lock.json
  packages/package.json
Labels: patch

#3726 [ST-6210] Allow Node >=18 in engines config
  package-lock.json
  package.json
Labels: patch

#3717 [GRAV-1370] [BpkOverlay] Add video overlay style
  examples/bpk-component-overlay/examples.js
  examples/bpk-component-overlay/stories.tsx
  packages/bpk-component-overlay/src/BpkOverlay.module.scss
  packages/bpk-component-overlay/src/BpkOverlay.tsx
  packages/bpk-component-overlay/src/__snapshots__/BpkOverlay-test.tsx.snap
Labels: minor

#3727 Revert "[NO JIRA]: Update compliation of stylesheets"
  package.json
  packages/bpk-stylesheets/webpack.config.babel.js
  scripts/transpilation/transform-js-scss-css-imports.js
Labels: patch

#3731 SDPLAT-26630: use GH_APP in workflows
  .github/workflows/_build.yml
  .github/workflows/label-check.yml
  .github/workflows/main.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
Labels: skip-changelog
