Repository Skyscanner/backpack, pull requests merged in 2025-04, with the labels that each got.

#3787 [QUAR-801][BpkOverlay] Update video overlay to align with heavy overlay design
  examples/bpk-component-overlay/examples.js
  examples/bpk-component-overlay/stories.tsx
  packages/bpk-component-overlay/src/BpkOverlay.module.scss
  packages/bpk-component-overlay/src/BpkOverlay.tsx
  packages/bpk-component-overlay/src/__snapshots__/BpkOverlay-test.tsx.snap
Labels: minor

#3485 [ARGG-1157][BpkTooltip]: Migrate tooltip to floating-ui
  examples/bpk-component-tooltip/examples.js
  examples/bpk-component-tooltip/examples.tsx
  examples/bpk-component-tooltip/stories.tsx
  packages/bpk-component-tooltip/index.ts
  packages/bpk-component-tooltip/src/BpkTooltip-test.tsx
  packages/bpk-component-tooltip/src/BpkTooltip.module.scss
  packages/bpk-component-tooltip/src/BpkTooltip.tsx
  packages/bpk-component-tooltip/src/BpkTooltipPortal-test.tsx
  packages/bpk-component-tooltip/src/BpkTooltipPortal.tsx
  packages/bpk-component-tooltip/src/__snapshots__/BpkTooltip-test.tsx.snap
  packages/bpk-component-tooltip/src/__snapshots__/BpkTooltipPortal-test.tsx.snap
  packages/bpk-component-tooltip/src/accessibility-test.tsx
Labels: major

#3768 [BD-9545][BpkLink] Add bpk-link--explicit for the new bpk-link design.
  examples/bpk-component-link/examples.js
  examples/bpk-component-link/stories.js
  packages/bpk-component-link/src/BpkLink.js
  packages/bpk-component-link/src/BpkLink.module.scss
  packages/bpk-mixins/_buttons.scss
  packages/bpk-mixins/_typography.scss
Labels: major

#3788 [Clover-nojira][BPKLink]Add overview storybook example for link component
  examples/bpk-component-link/examples.js
  examples/bpk-component-link/stories.js
Labels: skip-changelog

#3804 [BD-9736] [BpkPrice] Append data attribute to Price Element
  examples/bpk-component-price/examples.js
  examples/bpk-component-price/stories.js
  packages/bpk-component-price/src/BpkPrice-test.js
  packages/bpk-component-price/src/BpkPrice.js
Labels: minor

#3801 [No Jira][BpkIcon]Bump bpk-svgs from 20.1.1 to 20.4.1 & bump bpk-foundations-web from 19.3.0 to 19.4.1
  .eslintignore
  .prettierignore
  examples/bpk-component-icon/examples.js
  examples/bpk-component-icon/stories.js
  package-lock.json
  package.json
  packages/bpk-component-icon/all.tsx
  packages/package-lock.json
  packages/package.json
Labels: minor

#3806 [NO-JIRA][BpkInsetBanner] Fix UI issues
  examples/bpk-component-inset-banner/examples.tsx
  examples/bpk-component-inset-banner/stories.ts
  packages/bpk-component-inset-banner/README.md
  packages/bpk-component-inset-banner/src/BpkInsetBanner.module.scss
  packages/bpk-component-inset-banner/src/BpkInsetBanner.tsx
Labels: patch

#3782 [CLOVER-2987][BpkStar]Add Extra Large Rating Star
  examples/bpk-component-star-rating/examples.js
  packages/bpk-component-star-rating/src/BpkInteractiveStarRating.js
  packages/bpk-component-star-rating/src/BpkStar.js
  packages/bpk-component-star-rating/src/BpkStar.module.scss
  packages/bpk-component-star-rating/src/BpkStarRating.js
Labels: minor

#3814 [NoJira][BpkLink] Remove wrong tokens use.
  packages/bpk-mixins/_typography.scss
Labels: patch
