Repository Skyscanner/backpack, pull requests merged in 2025-09, with the labels that each got.

#3926 [No Jira][Maintenance]Update browserslist to align with browserslist-config-skyscanner.
  package.json
Labels: patch

#3921 Figma code connect
  .github/workflows/pr.yml
  .github/workflows/sync-figma-code-connect.yml
  .gitignore
  babel.config.js
  figma.config.json
  package-lock.json
  package.json
  packages/bpk-component-badge/src/BpkBadge.figma.tsx
  packages/bpk-component-button/src/BpkButtonV2/BpkButton.figma.tsx
  packages/bpk-component-image/src/BpkImage.figma.tsx
  packages/bpk-component-price/src/BpkPrice.figma.tsx
  tsconfig.declaration.json
  tsconfig.json
Labels: skip-changelog

#3942 [CLOVER-701][BpkBackgroundImage] Remove UNSAFE_componentWillReceiveProps usage
  packages/bpk-component-image/src/BpkBackgroundImage-test.tsx
  packages/bpk-component-image/src/BpkBackgroundImage.tsx
Labels: minor

#3943 [CLOVER-701][AnimateHeight] Remove UNSAFE_componentWillReceiveProps usage
  packages/bpk-animate-height/src/AnimateHeight.js
Labels: minor

#3929 [WOODPECKER-3717]Remove defaultProps
  packages/bpk-component-button/src/BpkButton.tsx
  packages/bpk-component-button/src/BpkButtonBase.tsx
  packages/bpk-component-button/src/common-types.ts
  packages/bpk-component-checkbox/src/BpkCheckbox.js
  packages/bpk-component-fieldset/src/BpkFieldset.js
  packages/bpk-component-flare/src/BpkContentBubble.js
  packages/bpk-component-flare/src/BpkFlareBar.js
  packages/bpk-component-form-validation/src/BpkFormValidation.js
  packages/bpk-component-info-banner/src/BpkInfoBannerInner.tsx
  packages/bpk-component-label/src/BpkLabel.js
  packages/bpk-component-link/src/BpkButtonLink.js
  packages/bpk-component-link/src/BpkLink.js
  packages/bpk-component-list/src/BpkList.js
  packages/bpk-component-list/src/BpkListItem.js
  packages/bpk-component-price/src/BpkPrice.js
  packages/bpk-component-radio/src/BpkRadio.js
  packages/bpk-component-select/src/BpkSelect.js
  packages/bpk-component-star-rating/src/BpkInteractiveStar.js
  packages/bpk-component-star-rating/src/BpkInteractiveStarRating.js
  packages/bpk-component-star-rating/src/BpkStar.js
  packages/bpk-component-star-rating/src/BpkStarRating.js
  packages/bpk-component-table/src/BpkTable.js
  packages/bpk-component-table/src/BpkTableCell.js
  packages/bpk-component-table/src/BpkTableHeadCell.js
  packages/bpk-component-textarea/src/BpkTextarea.js
Labels: minor

#3947 [BpkBlockQuote] Migrate blockquote to TS
  examples/bpk-component-blockquote/examples.tsx
  examples/bpk-component-blockquote/stories.tsx
  packages/bpk-component-blockquote/index.ts
  packages/bpk-component-blockquote/src/BpkBlockquote-test.tsx
  packages/bpk-component-blockquote/src/BpkBlockquote.tsx
  packages/bpk-component-blockquote/src/__snapshots__/BpkBlockquote-test.tsx.snap
  packages/bpk-component-blockquote/src/accessibility-test.tsx
  packages/bpk-component-blockquote/src/themeAttributes-test.ts
  packages/bpk-component-blockquote/src/themeAttributes.ts
Labels: minor, ai: copilot

#3949 [WOODPECKER-3717][BpkSkipLink][BpkThemeProvider]remove defaultProps
  packages/bpk-component-skip-link/src/BpkSkipLink.js
  packages/bpk-theming/src/BpkThemeProvider.js
Labels: minor

#3954 [AI] Add AGENTS.md to provide extra context
  AGENTS.md
Labels: skip-changelog, ai: copilot, code-connect

#3962 [CLOV-726]connect BpkChip to figma
  packages/bpk-component-accordion/src/BpkAccordion.figma.tsx
  packages/bpk-component-chip/src/BpkDismissibleChip.figma.tsx
  packages/bpk-component-chip/src/BpkDropdownChip.figma.tsx
  packages/bpk-component-chip/src/BpkSelectableChip.figma.tsx
Labels: skip-changelog, code-connect

#3970 [BpkInput][CLOV-740] Code connect to Figma
  packages/bpk-component-input/src/BpkInput.figma.tsx
Labels: skip-changelog, code-connect

#3972 [NO-JIRA][bpk-stylesheets] Add missed fallback bold fonts to backpack
  examples/bpk-fallback-fonts/examples.tsx
  examples/bpk-fallback-fonts/stories.tsx
  package-lock.json
  package.json
  packages/bpk-stylesheets/font.scss
  packages/package-lock.json
Labels: minor

#3948 [BpkTextArea] Migrate to Typescript
  examples/bpk-component-textarea/examples.tsx
  examples/bpk-component-textarea/stories.tsx
  packages/bpk-component-textarea/index.ts
  packages/bpk-component-textarea/src/BpkTextarea-test.tsx
  packages/bpk-component-textarea/src/BpkTextarea.tsx
  packages/bpk-component-textarea/src/__snapshots__/BpkTextarea-test.tsx.snap
  packages/bpk-component-textarea/src/accessibility-test.tsx
  packages/bpk-component-textarea/src/themeAttributes-test.ts
  packages/bpk-component-textarea/src/themeAttributes.ts
Labels: minor, ai: copilot
