Repository Skyscanner/backpack, pull requests merged in 2025-07, with the labels that each got.

#3862 [QUAR-864][BpkInsetBannerSponsored]-add new examples for sponsored banners with and without images
  examples/bpk-component-inset-banner-v2/examples.tsx
  examples/bpk-component-inset-banner-v2/stories.ts
Labels: minor

#3870 Add storybook essentials addon for extra useful features
  .storybook/main.ts
  package-lock.json
  package.json
Labels: skip-changelog

#3855 [Snyk] Security upgrade @skyscanner/stylelint-config-skyscanner from 12.2.1 to 13.1.0
  package-lock.json
  package.json
  packages/bpk-component-segmented-control/src/BpkSegmentedControl.module.scss
Labels: dependencies, patch

#3876 [maintainence] upgrade node to 22.x
  .nvmrc
  package-lock.json
  package.json
Labels: major, V38

#3885 [NO-JIRA][BpkRating] Fixed the issue where some BpkRating attributes were required
  packages/bpk-component-rating/src/BpkRating-test.tsx
  packages/bpk-component-rating/src/BpkRating.tsx
Labels: patch

#3886 [NO JIRA] Upgrade foundations dependencies
  package-lock.json
  package.json
  packages/package-lock.json
  packages/package.json
Labels: dependencies, minor

#3892 [CLOV-402][BpkCardList] Fix cardlist initially shown cards change issue
  examples/bpk-component-card-list/examples.tsx
  packages/bpk-component-card-list/src/BpkCardListRowRail/BpkCardListCarousel.tsx
  packages/bpk-component-card-list/src/BpkCardListRowRail/BpkCardListRowRailContainer.tsx
  packages/bpk-component-card-list/src/common-types.ts
Labels: patch

#3894 Revert "[BD-9759][BpkPopover] Add close button beside body"
  examples/bpk-component-popover/examples.js
  examples/bpk-component-popover/stories.js
  packages/bpk-component-popover/src/BpkPopover-test.tsx
  packages/bpk-component-popover/src/BpkPopover.module.scss
  packages/bpk-component-popover/src/BpkPopover.tsx
Labels: minor

#3891 [QUAR-991] [BpkInsetBannerSponsored] Add closeOnScrimClick prop to BpkBottomSheet
  packages/bpk-component-inset-banner/src/BpkInsetBannerV2/BpkInsetBannerSponsored.tsx
Labels: minor
