Repository Skyscanner/backpack, pull requests merged in 2025-03, with the labels that each got.

#3762 [NO-JIRA][BpkChipGroup] Align nudger margins in rail chip group with design
  packages/bpk-component-chip-group/src/Nudger.module.scss
Labels: minor

#3763 [QUAR-706][BpkPopover & BpkInsetBanner] Add custom z-index value
  packages/bpk-component-inset-banner/README.md
  packages/bpk-component-inset-banner/src/BpkInsetBanner-test.tsx
  packages/bpk-component-inset-banner/src/BpkInsetBanner.tsx
  packages/bpk-component-popover/src/BpkPopover.module.scss
  packages/bpk-component-popover/src/BpkPopover.tsx
Labels: minor

#3771 [MAT-2306][BpkDrawer] Update BpkDrawer by allowing dynamic width and animation
  packages/bpk-component-drawer/src/BpkDrawer.tsx
  packages/bpk-component-drawer/src/BpkDrawerContent.module.scss
  packages/bpk-component-drawer/src/BpkDrawerContent.tsx
  packages/bpk-component-drawer/src/__snapshots__/BpkDrawer-test.tsx.snap
Labels: minor

#3770 [GOOSE-148][BpkSegmentedControl] Refactor for use by Flights Search Controls
  examples/bpk-component-segmented-control/examples.module.scss
  examples/bpk-component-segmented-control/examples.tsx
  examples/bpk-component-segmented-control/stories.tsx
  packages/bpk-component-segmented-control/src/BpkSegmentedControl.module.scss
  packages/bpk-component-segmented-control/src/BpkSegmentedControl.tsx
Labels: patch

#3772 [PANGOO-2946][BpkPopover]Fix BpkDatepicker onClose
  packages/bpk-component-inset-banner/src/BpkInsetBanner.tsx
  packages/bpk-component-popover/src/BpkPopover.tsx
Labels: patch

#3773 [BD-9486][BpkPriceRange]Add BpkPriceRange component
  README.md
  examples/bpk-component-price-range/examples.tsx
  examples/bpk-component-price-range/stories.tsx
  packages/README.md
  packages/bpk-component-price-range/README.md
  packages/bpk-component-price-range/index.ts
  packages/bpk-component-price-range/src/BpkPriceMarker.module.scss
  packages/bpk-component-price-range/src/BpkPriceMarker.tsx
  packages/bpk-component-price-range/src/BpkPriceRange-test.tsx
  packages/bpk-component-price-range/src/BpkPriceRange.module.scss
  packages/bpk-component-price-range/src/BpkPriceRange.tsx
  packages/bpk-component-price-range/src/accessibility-test.tsx
  packages/bpk-component-price-range/src/common-types.ts
Labels: minor

#3774 [PANGOO-2905][BpkCheckbox]Checkbox With SVG
  packages/bpk-mixins/_forms.scss
Labels: patch

#3777 [NO-JIRA]Update support team
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: skip-changelog
